import fs from 'node:fs/promises'
import assert from 'node:assert/strict'

// Continúa el PostgreSQL aislado del suite financiero y usa las RPC vigentes reales.
export async function testCheckoutCaja(db, claims) {
  const fixture = JSON.parse(await fs.readFile(new URL('./checkout-caja.fixture.json', import.meta.url),'utf8'))
  for (const name of ['pedido_vendedor','pedido_vendedor_linea']) {
    const columns = fixture.tables.filter(c => c.name === name).map(c => `${c.col} ${c.col === 'id' ? 'bigint generated by default as identity primary key' : c.type}${c.col !== 'id' && c.default && !c.default.includes('nextval') ? ` default ${c.default}` : ''}`)
    await db.exec(`create table public.${name}(${columns.join(',')})`)
  }
  for (const f of fixture.functions) await db.exec(f.definition+';')
  await db.exec(`alter table public.producto add column precio_base numeric;
    alter table public.venta_evento add column if not exists linea_id bigint;
    drop view public.v_vtd_por_cobrar;
    create view public.v_vtd_por_cobrar as select id as venta_id,total from public.venta where numero like 'VTD-%' and cobro_exigible and estado<>'ANULADA' and not exists(select 1 from public.venta_pago where venta_id=venta.id);
    update public.sesion_caja set estado='ABIERTA' where id=900001;
    insert into public.producto(id,nombre,precio_base) values(990001,'Producto sintético',10);
    insert into public.perfil(id,nombre,rol,activo,email) values('00000000-0000-0000-0000-000000000009','Vendedora sintética','vendedor',true,'seller@test.invalid');
    insert into public.venta(id,numero,total,estado,cobro_exigible,cliente_id,ubicacion_id) values(890001,'VTD-TEST-1',150,'ABIERTA',true,null,990001),(890002,'VTD-TEST-2',60,'COMPLETADA',true,null,990001),(890003,'VTD-TEST-3',20,'ABIERTA',true,null,990001);
    insert into public.venta_linea(venta_id,producto_id,cantidad,precio_unitario) values(890001,990001,15,10),(890002,990001,6,10),(890003,990001,2,10);`)
  await db.exec(await fs.readFile(new URL('../migrations/20261007213559_checkout_caja_unificado.sql',import.meta.url),'utf8'))
  await claims('00000000-0000-0000-0000-000000000002')
  const seller='00000000-0000-0000-0000-000000000009'
  const line={producto_id:990001,cantidad_base:2,precio_unitario:10,sucursal_origen_id:2}
  const call=(key,options={})=>db.query(`select public.checkout_caja(p_lineas=>$1,p_pagos=>$2,p_sesion_id=>900001,p_idempotencia=>$3,p_cliente_id=>$4,p_descuento=>$5,p_saldo=>$6,p_vendedor_id=>$7,p_pedido_ids=>$8,p_quitadas=>$9,p_vtd_ids=>$10) result`,[JSON.stringify(options.lines??[line]),JSON.stringify(options.payments??[{metodo:'EFECTIVO',monto:170,recibido:200}]),key,options.customer??null,options.discount??0,options.balance??0,options.seller??seller,options.pedidos??[],JSON.stringify(options.quitadas??[]),options.vtds??[890001]])
  const count=async table=>Number((await db.query(`select count(*) as n from public.${table}`)).rows[0].n)
  const stock=async()=>Number((await db.query('select cantidad_base from public.stock_actual where producto_id=990001')).rows[0].cantidad_base)
  const before=await stock()
  const first=(await call('test-combo-1')).rows[0].result
  assert.equal(Number(first.total),170);assert.equal(Number(first.cambio),30);assert.equal(first.ventas.length,2)
  assert.equal(first.lineas.length,2);assert.equal(first.vendedor,'Vendedora sintética')
  assert.equal(await stock(),before-2,'La VTD no debe descontar stock por segunda vez')
  assert.equal(Number((await db.query('select sum(monto) total from public.movimiento_caja where venta_id=any($1)',[first.ventas])).rows[0].total),170)
  const counts=await Promise.all(['venta','venta_pago','movimiento_caja','cobro_caja'].map(count))
  assert.equal((await call('test-combo-1')).rows[0].result.id,first.id)
  assert.deepEqual(await Promise.all(['venta','venta_pago','movimiento_caja','cobro_caja'].map(count)),counts)
  await assert.rejects(()=>call('test-combo-1',{payments:[{metodo:'QR',monto:170}]}),/otro cobro/)
  await assert.rejects(()=>call('test-already-paid'),/ya está cobrada/)
  const digital=(await call('test-combo-2',{vtds:[890002],payments:[{metodo:'EFECTIVO',monto:30},{metodo:'QR',monto:50}]})).rows[0].result
  assert.equal(Number(digital.total),80)
  assert.equal(Number((await db.query("select sum(monto) total from public.venta_pago where venta_id=any($1) and metodo='QR'",[digital.ventas])).rows[0].total),50)
  const single=(await call('test-vtd-only',{lines:[],vtds:[890003],payments:[{metodo:'QR',monto:20}]})).rows[0].result
  assert.deepEqual(single.ventas,[890003]);assert.equal(Number(single.total),20)
  assert.equal((await db.query('select vendedor_id from public.venta where id=890003')).rows[0].vendedor_id,seller)
  const stockBeforeFailure=await stock();const salesBeforeFailure=await count('venta')
  await db.exec(`create function public.test_checkout_fail() returns trigger language plpgsql as $$begin if new.nota like 'Cobro VTD-FAIL%' then raise exception 'Fallo sintético en VTD';end if;return new;end$$;
    create trigger test_checkout_fail before insert on public.movimiento_caja for each row execute function public.test_checkout_fail();
    insert into public.venta(id,numero,total,estado,cobro_exigible,ubicacion_id) values(890004,'VTD-FAIL',50,'ABIERTA',true,990001);`)
  await assert.rejects(()=>call('test-rollback',{vtds:[890004],payments:[{metodo:'EFECTIVO',monto:70}]}),/Fallo sintético/)
  assert.equal(await stock(),stockBeforeFailure);assert.equal(await count('venta'),salesBeforeFailure+1,'Rollback de la venta nueva cuando falla la VTD')
  await db.exec(`insert into public.pedido_vendedor(id,numero_dia,estado,vendedor_id,sesion_caja_id) values(890010,1,'EN_CAJA','${seller}',900001);
    insert into public.pedido_vendedor_linea(id,pedido_id,orden,producto_id,es_personalizado) values(890010,890010,1,990001,false);`)
  const orderLine={...line,pedido_linea_id:890010,verificada:true}
  const pedido=(await call('test-pedido-combo',{lines:[line,orderLine],vtds:[],pedidos:[890010],payments:[{metodo:'EFECTIVO',monto:40}]})).rows[0].result
  assert.equal(Number(pedido.total),40)
  assert.equal((await db.query('select estado from public.pedido_vendedor where id=890010')).rows[0].estado,'COBRADO')
  assert.equal((await db.query('select vendedor_id from public.venta where id=$1',[pedido.ventas[0]])).rows[0].vendedor_id,seller)
  // Saldo confirmado: solo financia la venta nueva, sin inflar el ingreso de dinero.
  await db.exec(`insert into hermes.movimiento_cuenta(cliente_id,tipo,monto,idempotencia_clave,fecha_efectiva,creado_por)
    values((select id from hermes.cliente where pos_cliente_id=990001),'SALDO_APERTURA',-100,'test-checkout-credit',current_date,'test');`)
  const credit=(await call('test-checkout-saldo',{vtds:[],customer:990001,balance:10,payments:[{metodo:'EFECTIVO',monto:10}]})).rows[0].result
  assert.equal(Number(credit.total),20);assert.equal(Number(credit.saldo_favor),10)
  assert.equal(Number((await db.query('select sum(monto) total from public.movimiento_caja where venta_id=$1',[credit.ventas[0]])).rows[0].total),10)
  await assert.rejects(()=>call('test-vtd-credit',{lines:[],vtds:[890004],customer:990001,balance:10,payments:[{metodo:'EFECTIVO',monto:40}]}),/saldo exceden/)
  await db.exec(`update public.pedido_vendedor set estado='EN_CAJA' where id=890010`)
  await assert.rejects(()=>call('test-seller-conflict',{lines:[orderLine],vtds:[],pedidos:[890010],seller:'00000000-0000-0000-0000-000000000001',payments:[{metodo:'EFECTIVO',monto:20}]}),/Conserva el vendedor/)
  await assert.rejects(()=>call('test-pedido-unverified',{lines:[{...orderLine,verificada:false}],vtds:[],pedidos:[890010],payments:[{metodo:'EFECTIVO',monto:20}]}),/Falta verificar/)
  await db.exec(`insert into public.cliente(id,nombre,tipo_precio,activo) values(890020,'Cliente pedido sintético','mayorista',true);
    insert into public.pedido(id,categoria,cliente_id,total,subtotal,numero,estado) values(890020,'MAYOR',890020,40,40,'PED-COMPLETADO','COMPLETADO'),(890021,'MAYOR',890020,60,60,'PED-OTRO','ABIERTO');`)
  const pending=(await db.query('select * from public.pedidos_cobro_cliente(890020)')).rows
  assert(pending.some(p=>p.id===890020),'Los pedidos completados con deuda se pueden cobrar')
  const register=async key=> (await db.query("select public.registrar_cobro_cation(p_pedido_id=>890020,p_cliente_id=>890020,p_monto=>40,p_metodo=>'EFECTIVO',p_sesion_id=>900001,p_idempotencia=>$1) result",[key])).rows[0].result
  const paid=await register('test-paid-order-1')
  assert(!(await db.query('select * from public.pedidos_cobro_cliente(890020)')).rows.some(p=>p.id===890020),'Un pago propuesto ya reduce el importe sugerido')
  await claims('00000000-0000-0000-0000-000000000001');await db.query("select hermes.confirmar_pago($1,'test')",[paid.pagoId])
  await claims('00000000-0000-0000-0000-000000000002');const advance=await register('test-paid-order-2')
  assert.equal((await db.query('select no_imputar from hermes.pago where id=$1',[advance.pagoId])).rows[0].no_imputar,true)
  await claims('00000000-0000-0000-0000-000000000001');await db.query("select hermes.confirmar_pago($1,'test')",[advance.pagoId])
  assert.equal(Number((await db.query('select pendiente from hermes.v_partida_estado where pedido_id=890021')).rows[0].pendiente),60,'El pago dirigido no pasa al pedido siguiente')
  await claims('00000000-0000-0000-0000-000000000002')
  await db.exec(`insert into public.cliente(id,nombre,tipo_precio,activo) values(890030,'Cliente abono sintético','mayorista',true);
    insert into public.pedido(id,categoria,cliente_id,total,subtotal,numero,estado) values(890030,'MAYOR',890030,100,100,'PED-ABONO','COMPLETADO'),(890031,'MAYOR',890030,60,60,'PED-NO-TOCAR','ABIERTO');`)
  const abono=async (monto,key)=>(await db.query("select public.registrar_cobro_cation(p_pedido_id=>890030,p_cliente_id=>890030,p_monto=>$1,p_metodo=>'EFECTIVO',p_sesion_id=>900001,p_idempotencia=>$2) result",[monto,key])).rows[0].result
  const partial=await abono(25,'test-partial-specific-order')
  assert.equal(Number((await db.query('select * from public.pedidos_cobro_cliente(890030) where id=890030')).rows[0].pendiente),75,'El abono en revisión reduce el pendiente de este pedido')
  const excess=await abono(85,'test-excess-specific-order')
  assert.equal(Number((await db.query('select sum(monto) as total from hermes.pago_aplicacion where pago_id=$1',[excess.pagoId])).rows[0].total),75,'Solo se aplica la deuda no reservada del pedido elegido')
  await claims('00000000-0000-0000-0000-000000000001')
  await db.query("select hermes.confirmar_pago($1,'test')",[partial.pagoId]);await db.query("select hermes.confirmar_pago($1,'test')",[excess.pagoId])
  assert.equal(Number((await db.query('select pendiente from hermes.v_partida_estado where pedido_id=890031')).rows[0].pendiente),60,'El excedente no se aplica a otro pedido')
  assert.equal(Number((await db.query("select monto from hermes.movimiento_cuenta where pago_id=$1 and tipo='ANTICIPO'",[excess.pagoId])).rows[0].monto),-10,'El excedente queda como anticipo del cliente')
  assert.equal((await db.query("select has_function_privilege('anon','public.checkout_caja(jsonb,jsonb,bigint,text,bigint,numeric,numeric,uuid,bigint[],jsonb,bigint[])','EXECUTE') allowed")).rows[0].allowed,false)
  await claims(seller)
  await assert.rejects(()=>call('test-seller-not-cash',{vtds:[],payments:[{metodo:'EFECTIVO',monto:20}]}),/No autorizado/)
  await claims('00000000-0000-0000-0000-000000000003')
  await assert.rejects(()=>call('test-inactive-cash',{vtds:[],payments:[{metodo:'EFECTIVO',monto:20}]}),/No autorizado/)
  await claims('00000000-0000-0000-0000-000000000002')
  await db.exec("update public.sesion_caja set estado='CERRADA' where id=900001")
  assert.equal((await call('test-combo-1')).rows[0].result.id,first.id,'La respuesta perdida se recupera incluso después de cerrar el turno')
  await assert.rejects(()=>call('test-new-closed',{vtds:[],payments:[{metodo:'EFECTIVO',monto:20}]}),/cerrada/)
  console.log('OK: cobro único, pagos mixtos, reintento, rollback, stock sin duplicar, atribución, pedido verificado y destino en Hermes')
}
