import {PGlite} from '@electric-sql/pglite'
import fs from 'node:fs/promises'
import assert from 'node:assert/strict'
import { testOrigenMayorista } from './origen-mayorista.test.mjs'
import { testSincronizacionAutomatica } from './sincronizacion-automatica.test.mjs'
import { testSaldoFavor } from './saldo-favor.test.mjs'
const backup=JSON.parse(await fs.readFile(new URL('./schema.fixture.json',import.meta.url),'utf8'))
const meta=backup.metadata[0].metadata
const db=new PGlite()
await db.exec(`create role anon;create role authenticated;create role service_role;create role hermes_app;
create schema auth;create schema hermes;create schema storage;
create table storage.objects(bucket_id text,name text);
create function auth.jwt() returns jsonb language sql stable as $$select nullif(current_setting('request.jwt.claims',true),'')::jsonb$$;
create function auth.uid() returns uuid language sql stable as $$select (auth.jwt()->>'sub')::uuid$$;
set check_function_bodies=false;`)
const q=x=>'"'+x.replaceAll('"','""')+'"'
for(const e of meta.enums)await db.exec('create type '+q(e.schema)+'.'+q(e.name)+' as enum('+e.values.map(v=>"'"+v+"'").join(',')+');')
for(const t of meta.tables){
 const columns=t.columns.map(c=>{
  let def=c.default
  if(def&&def.startsWith('nextval('))def=null
  return q(c.name)+' '+c.type+(c.identity||c.default?.startsWith('nextval(')?' generated by default as identity':def?' default '+def:'')+(c.notnull?' not null':'')
 })
 await db.exec('create table '+q(t.schema)+'.'+q(t.name)+'('+columns.join(',')+');')
 for(const c of t.constraints??[])if(c.type!=='f')await db.exec('alter table '+q(t.schema)+'.'+q(t.name)+' add constraint '+q(c.name)+' '+c.definition+';')
}
for(const f of meta.functions)await db.exec(f+';')
await db.exec('grant usage,create on schema hermes to hermes_app;')
for(const r of (await db.query("select p.oid::regprocedure::text signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='hermes' and p.proname<>'rol_actual'")).rows){
 await db.exec('alter function '+r.signature+' owner to hermes_app;')
}
let views=[...backup.views]
while(views.length){
 const retry=[];let made=0
 for(const v of views)try{await db.exec('create view '+q(v.schema)+'.'+q(v.name)+' as '+v.definition);made++}catch(e){retry.push({...v,error:e.message})}
 if(!made)throw Error('Vistas pendientes: '+retry.map(v=>v.name+': '+v.error).join('\n'))
 views=retry
}
for(const t of meta.triggers??[])if(!t.includes('comision_'))await db.exec(t+';')
await db.exec(`create trigger comision_sync_partida_pedido after update of estado on public.pedido for each row execute function public.comision_trigger_sync_partida_pedido();`)
await db.exec(await fs.readFile(new URL('../migrations/20261001160704_hermes_transacciones_unificadas.sql',import.meta.url),'utf8'))
await db.exec(await fs.readFile(new URL('../migrations/20261001165305_hermes_actualizacion_por_eventos.sql',import.meta.url),'utf8'))
// Reproduce the production function owner: postgres-only tests miss auth schema permissions.
await db.exec('grant usage,create on schema hermes to hermes_app;alter function hermes.confirmar_pago(bigint,text) owner to hermes_app;')
await db.exec('grant select on public.v_pedido_hermes,public.v_cliente_hermes,public.v_venta_hermes to hermes_app;')
for(const r of (await db.query("select relname,relkind from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='hermes' and c.relkind in ('r','v')")).rows){
 await db.exec(`alter ${r.relkind==='v'?'view':'table'} hermes.${q(r.relname)} owner to hermes_app;`)
}
assert.equal((await db.query("select has_schema_privilege('hermes_app','auth','USAGE') permitted")).rows[0].permitted,false)
await db.exec(await fs.readFile(new URL('../migrations/20261001212417_hermes_identidad_del_operador.sql',import.meta.url),'utf8'))
assert.equal((await db.query("select has_schema_privilege('hermes_app','auth','USAGE') permitted")).rows[0].permitted,true)
assert.equal((await db.query("select has_schema_privilege('hermes_app','auth','CREATE') permitted")).rows[0].permitted,false)
// Managed Supabase's postgres cannot grant USAGE on auth (supabase_admin owns it).
// Reproduce the resulting live ACL, then validate without any auth schema grant.
await db.exec('revoke usage on schema auth from hermes_app;')
await db.exec(await fs.readFile(new URL('../migrations/20261001212930_hermes_identidad_sin_acceso_auth.sql',import.meta.url),'utf8'))
assert.equal((await db.query("select has_schema_privilege('hermes_app','auth','USAGE') permitted")).rows[0].permitted,false)
console.log('Migración compilada en PostgreSQL aislado')

// Fixtures are synthetic and never written to Supabase.
await db.exec(`insert into public.perfil(id,nombre,rol,activo,hermes_acceso,email) values
('00000000-0000-0000-0000-000000000001','Admin prueba','admin',true,true,'admin@test.invalid'),
('00000000-0000-0000-0000-000000000002','Caja prueba','cajero',true,false,'caja@test.invalid'),
('00000000-0000-0000-0000-000000000003','Inactivo prueba','cajero',false,false,'inactivo@test.invalid');
insert into public.cliente(id,nombre,tipo_precio,documento,activo) values(900001,'Cliente prueba','mayorista','TEST',true);
insert into public.sesion_caja(id,caja_id,estado,monto_apertura) values(900001,1,'ABIERTA',0);
`)
const claims=async(sub)=>db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub,role:'authenticated',email:'test@example.invalid'})])
await claims('00000000-0000-0000-0000-000000000002')
const call=(key,amount=25,extra={})=>db.query(`select public.registrar_cobro_hermes(p_cliente_id=>900001,p_monto=>$1,p_metodo=>'EFECTIVO',p_sesion_id=>900001,p_idempotencia=>$2,p_no_imputar=>$3,p_aplicaciones=>$4) result`,[amount,key,extra.noImputar??false,extra.apps??null])
const first=(await call('test-cobro-1')).rows[0].result
assert(first.pagoId&&first.movementId)
assert.equal((await call('test-cobro-1')).rows[0].result.movementId,first.movementId)
await assert.rejects(()=>call('test-cobro-1',26),/datos diferentes/)
assert.equal((await db.query("select count(*)::int n from hermes.pago")).rows[0].n,1)
assert.equal((await db.query("select estado from hermes.pago")).rows[0].estado,'PROPUESTO')
assert.equal(Number((await db.query("select saldo_confirmado::numeric s from hermes.v_saldo_cliente where cliente_id=900001")).rows[0].s),0)
await assert.rejects(()=>call('test-bad-app',25,{apps:[{partida_id:999999,monto:25}]}))
assert.equal((await db.query("select count(*)::int n from public.movimiento_caja")).rows[0].n,1,'El error del reparto debe revertir caja')
await assert.rejects(()=>call('test-conflict',25,{noImputar:true,apps:[{partida_id:999999,monto:25}]}),/no admite reparto/)
await claims('00000000-0000-0000-0000-000000000003')
await assert.rejects(()=>call('test-inactivo'),/No autorizado/)
await claims('00000000-0000-0000-0000-000000000002')
await db.exec("update public.sesion_caja set estado='CERRADA' where id=900001")
await assert.rejects(()=>call('test-cerrada'),/cerrada/)
assert.equal((await call('test-cobro-1')).rows[0].result.movementId,first.movementId,'Retry succeeds after closing cash')
console.log('OK: registro conjunto, pago propuesto, idempotencia, cambio de intención, rollback, permisos y caja cerrada')
await db.exec("update public.sesion_caja set estado='ABIERTA' where id=900001")
await db.exec("update hermes.cliente_credito set plazo_dias=45, limite_credito=5000 where cliente_id=900001; update public.cliente set nombre='Cliente renombrado' where id=900001")
assert.equal((await db.query("select plazo_dias from hermes.cliente_credito where cliente_id=900001")).rows[0].plazo_dias,45)
await db.exec("insert into hermes.contador_documento(tipo,serie,ultimo_valor) values('PARTIDA','TEST',0)")
await db.exec("insert into public.pedido(id,categoria,cliente_id,total,subtotal,numero) values(900010,'MAYOR',900001,100,100,'TEST-PED-1')")
await db.exec("update public.pedido set estado='COMPLETADO',recibido_en='2026-09-30T15:00:00Z' where id=900010")
const partida=(await db.query("select id,fecha_entrega,total from hermes.partida_abierta where pedido_id=900010")).rows[0]
assert(partida?.id,'Completar el pedido abre su partida')
assert.equal(Number(partida.total),100)
assert.equal(partida.fecha_entrega.toISOString().slice(0,10),'2026-09-30')
await db.query("select hermes.sincronizar_pedido_pos(900010,'2026-10-01')")
assert.equal((await db.query("select fecha_entrega from hermes.partida_abierta where id=$1",[partida.id])).rows[0].fecha_entrega.toISOString().slice(0,10),'2026-09-30')
assert.equal((await db.query("select count(*)::int n from hermes.partida_abierta where pedido_id=900010")).rows[0].n,1)
const allocated=(await call('test-repartido',80,{apps:[{partida_id:partida.id,monto:80}]})).rows[0].result
const stale=(await call('test-repartido-otro',80,{apps:[{partida_id:partida.id,monto:80}]})).rows[0].result
await assert.rejects(()=>db.query("select hermes.confirmar_pago($1,'test')",[allocated.pagoId]),/rol gerente/)
await claims('00000000-0000-0000-0000-000000000001')
await db.query("select hermes.confirmar_pago($1,'test')",[allocated.pagoId])
await assert.rejects(()=>db.query("select hermes.confirmar_pago($1,'test')",[stale.pagoId]),/deuda vigente/)
assert.equal(Number((await db.query("select pendiente from hermes.v_partida_estado where partida_id=$1",[partida.id])).rows[0].pendiente),20)
await claims('00000000-0000-0000-0000-000000000002')
const advance=(await call('test-anticipo-libre',10,{noImputar:true})).rows[0].result
await claims('00000000-0000-0000-0000-000000000001')
await db.query("select hermes.confirmar_pago($1,'test')",[advance.pagoId])
assert.equal((await db.query("select count(*)::int n from hermes.pago_aplicacion where pago_id=$1",[advance.pagoId])).rows[0].n,0)
assert.equal((await db.query("select tipo::text t from hermes.movimiento_cuenta where pago_id=$1",[advance.pagoId])).rows[0].t,'ANTICIPO')
assert.equal((await db.query("select has_function_privilege('anon','public.registrar_cobro_hermes(bigint,bigint,numeric,public.metodo_pago,bigint,text,boolean,jsonb,text)','EXECUTE') permitted")).rows[0].permitted,false)
assert.equal((await db.query("select has_function_privilege('authenticated','hermes.registrar_movimiento_pos(bigint)','EXECUTE') permitted")).rows[0].permitted,false)
console.log('OK: crédito preservado, partida y entrega únicas, fechas históricas, confirmación humana, reparto vigente, anticipo libre y RPC privadas')
await db.exec("insert into hermes.evidencia(id,storage_path) values(900001,'prueba/recibo.pdf'),(900002,'prueba/faltante.pdf');insert into storage.objects values('documentos-expediente','prueba/recibo.pdf')")
const beforeReceipt=(await db.query('select monto,estado from hermes.pago where id=$1',[allocated.pagoId])).rows[0]
await claims('00000000-0000-0000-0000-000000000002')
await assert.rejects(()=>db.query('select hermes.asociar_comprobante_pago($1,900001)',[allocated.pagoId]),/rol no puede/)
await claims('00000000-0000-0000-0000-000000000001')
await assert.rejects(()=>db.query('select hermes.asociar_comprobante_pago(999999,900001)'),/Pago no existe/)
await assert.rejects(()=>db.query('select hermes.asociar_comprobante_pago($1,999999)',[allocated.pagoId]),/Evidencia no existe/)
await assert.rejects(()=>db.query('select hermes.asociar_comprobante_pago($1,900002)',[allocated.pagoId]),/archivo del comprobante/)
assert.equal((await db.query('select hermes.asociar_comprobante_pago($1,900001) result',[allocated.pagoId])).rows[0].result.evidencia_id,900001)
assert.equal((await db.query('select hermes.asociar_comprobante_pago($1,null) result',[allocated.pagoId])).rows[0].result.evidencia_id,null)
assert.deepEqual((await db.query('select monto,estado from hermes.pago where id=$1',[allocated.pagoId])).rows[0],beforeReceipt)
assert.equal((await db.query("select has_function_privilege('anon','hermes.asociar_comprobante_pago(bigint,bigint)','EXECUTE') permitted")).rows[0].permitted,false)
assert.equal((await db.query("select has_table_privilege('service_role','hermes.pago','UPDATE') permitted")).rows[0].permitted,false)
console.log('OK: comprobante autorizado, archivo disponible, vínculo reversible y saldo/estado preservados')
await testOrigenMayorista(db, claims)
await testSincronizacionAutomatica(db, claims)
await testSaldoFavor(db, claims)
await db.close()
