import { PGlite } from '@electric-sql/pglite'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'

// Definitions and constraints read from the live schema; all writes stay in memory.
// Numbering uses a test-only trigger. This suite exercises quote persistence, not numbering.
const fixture = JSON.parse(await fs.readFile(new URL('./cotizaciones.fixture.json', import.meta.url), 'utf8'))
const db = new PGlite()
const q = (s) => '"' + s.replaceAll('"', '""') + '"'
try {
  await db.exec('create role anon; create role authenticated; create role service_role; create table sucursal(id bigint primary key); create table familia(id bigint primary key);')
  for (const e of fixture.metadata.enums) {
    await db.exec('create type ' + q(e.name) + ' as enum (' + e.values.map(v => "'" + v.replaceAll("'", "''") + "'").join(',') + ');')
  }
  for (const t of fixture.metadata.tables) {
    const columns = t.columns.map(c => q(c.name) + ' ' + c.type +
      (c.identity || c.default?.startsWith('nextval(') ? ' generated by default as identity' : c.generated ? ' generated always as (' + c.default + ') stored' : c.default ? ' default ' + c.default : '') +
      (c.notnull ? ' not null' : ''))
    await db.exec('create table ' + q(t.name) + '(' + columns.join(',') + ');')
  }
  for (const foreignKeys of [false, true]) for (const t of fixture.metadata.tables) for (const c of t.constraints ?? []) {
    if ((c.type === 'f') !== foreignKeys) continue
    await db.exec('alter table ' + q(t.name) + ' add constraint ' + q(c.name) + ' ' + c.definition + ';')
  }
  for (const f of fixture.functions) await db.exec(f + ';')
  await db.exec(`
    create function test_numero() returns trigger language plpgsql as $$
    begin if TG_OP='INSERT' then NEW.numero := 'TEST-' || NEW.id; end if; return NEW; end $$;
    create trigger test_numero before insert on cotizacion for each row execute function test_numero();
    create trigger trg_solicitante_coherente before insert or update of solicitante_id, cliente_id
      on cotizacion for each row execute function fn_solicitante_coherente();
    insert into sucursal values (1),(2);
    insert into cliente(nombre,tipo_precio) values ('Institución A','institucion'),('Corporación B','corporativo');
    insert into cliente_contacto(cliente_id,nombre) values (1,'Ana'),(1,'Bruno'),(2,'Carla');
    insert into producto(nombre,unidad_base) values ('Cable','METRO');
    insert into presentacion(producto_id,nombre,factor_unidad_base) values (1,'Paquete',4);
    revoke execute on function public.crear_cotizacion(categoria_pedido,jsonb,bigint,text,numeric,date,text,text,condicion_pago,date,bigint,metodo_pago) from public,anon;
    grant execute on function public.crear_cotizacion(categoria_pedido,jsonb,bigint,text,numeric,date,text,text,condicion_pago,date,bigint,metodo_pago) to authenticated,service_role;
  `)
  const lines = [{ es_personalizado: true, descripcion: 'Servicio', cantidad_base: 2, precio_unitario: 17.5, precio_lista: 20, unidad_medida: 'METRO', nota: 'Entrega coordinada', precio_modificado: true, modificado_por: 'vendedor@test' }]
  const get = async (id) => (await db.query('select * from cotizacion where id=$1', [id])).rows[0]
  const getLines = async (id) => (await db.query('select * from cotizacion_linea where cotizacion_id=$1 order by id', [id])).rows
  const edit = async (id, version, cliente = 1, solicitante = 2, payload = lines) => db.query(`
    select actualizar_cotizacion(p_cotizacion_id=>$1,p_version_actual=>$2,p_categoria=>'INSTITUCIONAL',
      p_lineas=>$3::jsonb,p_cliente_id=>$4,p_solicitante_id=>$5,p_notas=>'Notas editadas',
      p_condicion_pago=>'CREDITO',p_medio_pago=>'TRANSFERENCIA')`, [id,version,JSON.stringify(payload),cliente,solicitante])
  const id = (await db.query("select crear_cotizacion('INSTITUCIONAL',$1::jsonb,p_cliente_id=>1,p_solicitante_id=>1) id", [JSON.stringify(lines)])).rows[0].id
  await edit(id, (await get(id)).version)
  assert.equal((await get(id)).solicitante_id, 2)
  assert.equal((await get(id)).solicitado_por, 'Ana', 'Reproduce el nombre antiguo pese a cambiar el ID')

  await db.exec(await fs.readFile(new URL('../migrations/20261003223538_cotizaciones_identidad_duplicacion_atomica.sql', import.meta.url), 'utf8'))
  await db.exec(await fs.readFile(new URL('../migrations/20261003224852_cotizaciones_condiciones_comerciales.sql', import.meta.url), 'utf8'))
  await edit(id, (await get(id)).version)
  assert.equal((await get(id)).solicitado_por, 'Bruno', 'Repara un borrador con nombre desactualizado al guardar')
  await edit(id, (await get(id)).version, 2, 3)
  const changed = await get(id)
  assert.equal(changed.cliente_id, 2)
  assert.equal(changed.solicitante_id, 3)
  assert.equal(changed.solicitado_por, 'Carla')
  assert.equal(changed.notas, 'Notas editadas')
  assert.equal(changed.condicion_pago, 'CREDITO')
  assert.equal(changed.medio_pago, 'TRANSFERENCIA')
  assert.equal(Number(changed.total), 35)
  await edit(id, changed.version, 2, null)
  assert.equal((await get(id)).solicitante_id, null)
  assert.equal((await get(id)).solicitado_por, null, 'Quitar solicitante también quita el nombre')

  await edit(id, (await get(id)).version, 2, 3)
  const before = await get(id), beforeLines = await getLines(id)
  await assert.rejects(edit(id, before.version, 2, 1), /no pertenece a este cliente/)
  await assert.rejects(edit(id, before.version - 1, 2, 3), /otra sesión/)
  await assert.rejects(edit(id, null, 2, 3), /otra sesión/)
  await assert.rejects(edit(id, before.version, 2, 3, [{...lines[0], cantidad_base: -1}]), /positiva/)
  await assert.rejects(edit(id, before.version, 2, 3, null), /array no vacío/)
  assert.deepEqual(await get(id), before, 'Los errores conservan el encabezado completo')
  assert.deepEqual(await getLines(id), beforeLines, 'Los errores conservan todas las líneas')

  const copyId = (await db.query(`
    select crear_cotizacion('CORPORATIVO',$1::jsonb,p_cliente_id=>2,p_solicitante_id=>3,
      p_notas=>'Condiciones de entrega de la copia',p_condicion_pago=>'CONTADO',p_condiciones_comerciales=>'Entrega en 72 horas') id`, [JSON.stringify(lines)])).rows[0].id
  const copy = await get(copyId), copyLines = await getLines(copyId)
  assert.notEqual(copy.numero, before.numero)
  assert.equal(copy.version, 0)
  assert.equal(copy.solicitado_por, 'Carla')
  assert.equal(copy.notas, 'Condiciones de entrega de la copia')
  assert.equal(copy.condiciones_comerciales, 'Entrega en 72 horas')
  assert.equal(copyLines[0].unidad_medida, 'METRO')
  assert.equal(copyLines[0].nota, 'Entrega coordinada')
  assert.equal(copyLines[0].precio_modificado, true)
  assert.equal(copyLines[0].modificado_por, 'vendedor@test')
  await edit(copyId, copy.version, 1, 1)
  assert.equal((await get(copyId)).solicitado_por, 'Ana')
  assert.equal((await get(copyId)).condiciones_comerciales, 'Entrega en 72 horas', 'Los clientes anteriores mantienen las condiciones comerciales')
  await db.query(`select actualizar_cotizacion($1,$2,'INSTITUCIONAL',$3::jsonb,p_cliente_id=>1,p_solicitante_id=>1,p_condiciones_comerciales=>'')`, [copyId,(await get(copyId)).version,JSON.stringify(lines)])
  assert.equal((await get(copyId)).condiciones_comerciales, null, 'El formulario puede borrar explícitamente las condiciones')
  assert.deepEqual(await get(id), before, 'Editar la copia no modifica el original')

  await db.query("update cotizacion set estado='APROBADA' where id=$1", [id])
  await db.exec("update cliente_contacto set nombre='Carla actualizada',activo=false where id=3")
  assert.equal((await get(id)).solicitado_por, 'Carla', 'Documento aprobado conserva el nombre histórico')
  await assert.rejects(edit(id, before.version, 2, 3), /en borrador/)
  await assert.rejects(edit(copyId, (await get(copyId)).version, 2, 3), /desactivado/)
  // Un borrador que ya tenía el contacto ahora inactivo se puede editar sin cambiarlo.
  await db.query("update cotizacion set estado='BORRADOR' where id=$1", [id])
  await edit(id, (await get(id)).version, 2, 3)
  assert.equal((await get(id)).solicitado_por, 'Carla')

  const legacy = (await db.query("select crear_cotizacion('MAYOR',$1::jsonb,p_cliente_id=>1) id", [JSON.stringify(lines)])).rows[0].id
  assert.equal((await get(legacy)).notas, null, 'Clientes antiguos siguen usando la firma sin notas')
  const catalogue = [{producto_id:1,presentacion_id:1,cantidad_presentacion:2,precio_unitario:17.5,sucursal_origen_id:1}]
  const catalogId = (await db.query("select crear_cotizacion('MAYOR',$1::jsonb,p_cliente_id=>1) id", [JSON.stringify(catalogue)])).rows[0].id
  assert.equal(Number((await getLines(catalogId))[0].cantidad_base), 8)
  assert.equal(Number((await get(catalogId)).total), 35)
  const privileges = (await db.query(`
    select count(*) total, bool_and(not p.prosecdef) invoker,
      bool_and(not has_function_privilege('anon',p.oid,'EXECUTE')) no_anon,
      bool_and(has_function_privilege('authenticated',p.oid,'EXECUTE')) authenticated
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('crear_cotizacion','actualizar_cotizacion')`)).rows[0]
  assert.equal(privileges.total, 2)
  assert.equal(privileges.invoker, true)
  assert.equal(privileges.no_anon, true)
  assert.equal(privileges.authenticated, true)
  console.log('Cotizaciones: reproducción del error, cambio/limpieza de solicitante, cambio de cliente, copias completas, conflictos, rollback, contactos inactivos y permisos OK.')
} catch (error) {
  console.error(error.message, error.query ?? '')
  process.exitCode = 1
} finally {
  await db.close()
}
