import assert from 'node:assert/strict'
import fs from 'node:fs/promises'

// Integración sobre PostgreSQL aislado; ningún dato de cliente real se escribe aquí.
export async function testSaldoFavor(db,claims) {
 const fixture=JSON.parse(await fs.readFile(new URL('./saldo-favor.fixture.json',import.meta.url),'utf8'))
 const quote=x=>'"'+x.replaceAll('"','""')+'"'
 for(const t of fixture.tables.filter(t=>t.schema==='public')) {
  const exists=(await db.query('select to_regclass($1) t',[`${t.schema}.${t.name}`])).rows[0].t
  if(!exists)await db.exec(`create table public.${quote(t.name)} (id bigint generated by default as identity primary key)`)
  for(const c of t.columns) {
   if((await db.query('select 1 from information_schema.columns where table_schema=$1 and table_name=$2 and column_name=$3',[t.schema,t.name,c.name])).rows.length)continue
   let def=c.default
   if(def?.includes('nextval(')||['precio_modificado','subtotal'].includes(c.name)&&def?.includes('precio_'))def=null
   await db.exec(`alter table public.${quote(t.name)} add column ${quote(c.name)} ${c.type}${def?' default '+def:''}`)
  }
 }
 await db.exec(`alter table public.contador_documento add unique(tipo,anio);
 create table public.pedido_evento(id bigint generated by default as identity,pedido_id bigint,accion text,motivo text,estado_previo text,usuario text);
 create table public.ubicacion(id bigint primary key,sucursal_id bigint);
 create table public.sucursal(id bigint primary key,nombre text);
 create table public.stock_actual(producto_id bigint,ubicacion_id bigint,cantidad_base numeric,primary key(producto_id,ubicacion_id));
 create table public.kardex_transacciones(id bigint generated by default as identity primary key,presentacion_id bigint,ubicacion_id bigint,cantidad numeric,referencia text,tipo_movimiento text,idempotencia_clave text unique);
 alter table public.presentacion add column es_base boolean default true,add column activo boolean default true;
 create or replace function public.app_rol_actual() returns text language sql stable as $$select rol::text from public.perfil where id=auth.uid() and activo$$;
 create function public.app_puede_revertir_venta(bigint,text) returns text language sql stable as $$select case when public.app_rol_actual() in ('admin','gerente') then null else 'Solo gerencia puede anular' end$$;
 create function public.permite_sobregiro_sucursal(bigint,bigint) returns boolean language sql as $$select false$$;
 create function public.saldo_vendible(bigint[],bigint) returns table(vendible numeric,reservado numeric,motivo text) language sql as $$select sum(s.cantidad_base),0::numeric,null::text from public.stock_actual s join public.ubicacion u on u.id=s.ubicacion_id where s.producto_id=any($1) and u.sucursal_id=$2$$;
 create function public.registrar_salida(bigint,bigint,numeric,text,text,date,text,boolean) returns bigint language plpgsql as $$declare mid bigint;pid bigint;begin select producto_id into pid from public.presentacion where id=$1;update public.stock_actual set cantidad_base=cantidad_base-$3 where producto_id=pid and ubicacion_id=$2;insert into public.kardex_transacciones(presentacion_id,ubicacion_id,cantidad,referencia,tipo_movimiento,idempotencia_clave) values($1,$2,-$3,$4,'SALIDA',$7) returning id into mid;return mid;end$$;
 create function public.registrar_entrada(bigint,bigint,numeric,text,text,date,text,text) returns bigint language plpgsql as $$declare mid bigint;pid bigint;begin select producto_id into pid from public.presentacion where id=$1;update public.stock_actual set cantidad_base=cantidad_base+$3 where producto_id=pid and ubicacion_id=$2;insert into public.kardex_transacciones(presentacion_id,ubicacion_id,cantidad,referencia,tipo_movimiento,idempotencia_clave) values($1,$2,$3,$4,'ENTRADA',$8) returning id into mid;return mid;end$$;
 create view public.v_vtd_por_cobrar as select id,total from public.venta where false;`)
 for(const f of fixture.functions)await db.exec(f+';')
 await db.exec(await fs.readFile(new URL('../migrations/20261004005854_saldo_favor_ventas_pedidos.sql',import.meta.url),'utf8'))
 await db.exec(`insert into public.ubicacion values(990001,2);insert into public.sucursal values(2,'Tienda prueba');insert into public.presentacion(id,producto_id,factor_unidad_base) values(990001,990001,1);insert into public.stock_actual values(990001,990001,100);
 update public.sesion_caja set cajero_id='00000000-0000-0000-0000-000000000002' where id=900001;
 insert into public.cliente(id,nombre,tipo_precio,activo) values(990001,'Acreedor sintético','corporativo',true),(990002,'Acreedor sintético 2','institucion',true),(990003,'Retail sintético','retail',true);
 insert into hermes.movimiento_cuenta(cliente_id,tipo,monto,idempotencia_clave,fecha_efectiva,creado_por) values((select id from hermes.cliente where pos_cliente_id=990001),'SALDO_APERTURA',-2193,'saldo-test-apertura',current_date,'prueba'),((select id from hermes.cliente where pos_cliente_id=990002),'SALDO_APERTURA',-100,'saldo-test-apertura-2',current_date,'prueba');`)
 const caja='00000000-0000-0000-0000-000000000002',admin='00000000-0000-0000-0000-000000000001'
 await claims(caja)
 const sale=(key,saldo=228.5,pagos=[],client=990001,unit=228.5)=>db.query(`select public.registrar_venta_con_saldo($1,$2,900001,$3,$4,0,'ignorado',$5) r`,[JSON.stringify([{producto_id:990001,cantidad_base:1,precio_unitario:unit,precio_lista:unit,sucursal_origen_id:2}]),JSON.stringify(pagos),client,saldo,key])
 const available=(client,order=null)=>db.query('select public.consultar_saldo_disponible($1,$2) r',[client,order]).then(r=>r.rows[0].r)
 const balance=client=>db.query('select saldo_confirmado s from hermes.v_saldo_cliente where cliente_id=(select id from hermes.cliente where pos_cliente_id=$1)',[client]).then(r=>Number(r.rows[0].s))
 const counts=()=>db.query(`select (select count(*)::int from public.venta) ventas,(select count(*)::int from public.movimiento_caja) caja,(select count(*)::int from public.saldo_cliente_uso) usos,(select cantidad_base from public.stock_actual where producto_id=990001) stock`).then(r=>r.rows[0])
 const before=await counts()
 const first=(await sale('saldo-test-venta')).rows[0].r
 assert.equal(Number(first.saldo_favor_aplicado),228.5);assert.equal(Number(first.saldo_favor_restante),1964.5)
 assert.equal(await balance(990001),-1964.5)
 assert.equal((await counts()).caja,before.caja,'No crea dinero nuevo cuando todo se paga con saldo')
 assert.equal(Number((await counts()).stock),Number(before.stock)-1)
 assert.equal((await sale('saldo-test-venta')).rows[0].r.venta_id,first.venta_id,'Reintento no consume dos veces')
 await assert.rejects(()=>sale('saldo-test-venta',200,[{metodo:'EFECTIVO',monto:28.5}]),/otra venta|distintos/)
 const snapshot=await counts()
 await assert.rejects(()=>sale('saldo-test-exceso',2000,[],990001,2000),/saldo disponible cambió/)
 assert.deepEqual(await counts(),snapshot,'Saldo insuficiente revierte venta, stock y aplicaciones')
 await assert.rejects(()=>sale('saldo-test-total',10,[],990001),/no coincide/)
 await assert.rejects(()=>sale('saldo-test-retail',228.5,[],990003),/mayoristas/)
 const mixed=(await sale('saldo-test-mixto',100,[{metodo:'EFECTIVO',monto:128.5,recibido:150}],990002)).rows[0].r
 assert.equal(await balance(990002),0)
 assert.equal(Number((await db.query('select monto from public.movimiento_caja where venta_id=$1',[mixed.venta_id])).rows[0].monto),128.5,'Solo entra la diferencia a caja')
 await claims(admin)
 const summary=(await db.query('select public.resumen_turno(900001) r')).rows[0].r
 assert.equal(Number(summary.saldo_favor_aplicado),328.5)
 await db.query('select public.anular_venta($1,$2,900001,$3)',[first.venta_id,'admin@test.invalid','Prueba de reversión'])
 assert.equal(await balance(990001),-2193,'Anular devuelve el saldo original')
 assert.equal(Number((await counts()).stock),Number(before.stock)-1,'Solo permanece la venta mixta')
 await db.query('select public.anular_venta($1,$2,900001,$3)',[mixed.venta_id,'admin@test.invalid','Prueba de reversión mixta'])
 assert.equal(await balance(990002),-100)
 assert.equal(Number((await available(990002)).disponible),100,'La devolución no crea una segunda fuente de fondos')
 const order=(await db.query(`insert into public.pedido(categoria,cliente_id,total,subtotal,numero) values('CORPORATIVO',990001,228.5,228.5,'SALDO-PEDIDO') returning id`)).rows[0].id
 const afterOrder=await balance(990001)
 assert.equal(afterOrder,-1964.5)
 await claims(caja)
 const orderUse=()=>db.query(`select public.aplicar_saldo_pedido($1,228.5,900001,'saldo-test-pedido') r`,[order])
 await orderUse();await orderUse()
 assert.equal(await balance(990001),afterOrder,'Aplicar al pedido no descuenta el cargo por segunda vez')
 assert.equal(Number((await db.query('select pendiente from hermes.v_partida_estado where pedido_id=$1',[order])).rows[0].pendiente),0)
 assert.equal((await db.query('select estado::text s from hermes.partida_abierta where pedido_id=$1',[order])).rows[0].s,'PAGADA')
 await claims(admin)
 await db.query(`select public.anular_pedido($1,'Prueba de reversión','admin@test.invalid')`,[order])
 assert.equal(await balance(990001),-2193)
 assert.equal(Number((await available(990001)).disponible),2193)
 await db.exec(`insert into public.cliente(id,nombre,tipo_precio,activo) values(990004,'Anticipo sintético','corporativo',true);`)
 await claims(caja)
 const pendingAdvance=(await db.query(`select public.registrar_cobro_cation(p_cliente_id=>990004,p_monto=>50,p_metodo=>'QR',p_sesion_id=>900001,p_idempotencia=>'saldo-anticipo-test',p_no_imputar=>true) r`)).rows[0].r
 assert.equal(Number((await available(990004)).disponible),0,'Los pagos propuestos no son saldo disponible')
 await assert.rejects(()=>sale('saldo-propuesto-no-usable',1,[],990004,1),/saldo disponible cambió/)
 await claims(admin)
 await db.query(`select hermes.confirmar_pago($1,'admin@test.invalid')`,[pendingAdvance.pagoId])
 await claims(caja)
 const advanceSale=(await sale('saldo-anticipo-confirmado',20,[],990004,20)).rows[0].r
 assert.equal(Number((await available(990004)).disponible),30)
 assert.equal(Number((await db.query('select saldo_favor from hermes.v_anticipo_cliente where pago_id=$1',[pendingAdvance.pagoId])).rows[0].saldo_favor),30,'El anticipo muestra solo lo que queda tras su consumo')
 assert.equal(Number((await db.query('select imputado from hermes.v_anticipo_cliente where pago_id=$1',[pendingAdvance.pagoId])).rows[0].imputado),20,'El desglose del conciliador incluye el saldo ya utilizado')
 await claims(admin)
 await db.query('select public.anular_venta($1,$2,900001,$3)',[advanceSale.venta_id,'admin@test.invalid','Reversión de anticipo'])
 assert.equal(Number((await db.query('select saldo_favor from hermes.v_anticipo_cliente where pago_id=$1',[pendingAdvance.pagoId])).rows[0].saldo_favor),50)
 const mixedOrder=(await db.query(`insert into public.pedido(categoria,cliente_id,total,subtotal,numero) values('INSTITUCIONAL',990002,228.5,228.5,'SALDO-PEDIDO-MIXTO') returning id`)).rows[0].id
 await claims(caja)
 const orderPayment=(await db.query(`select public.aplicar_saldo_pedido($1,100,900001,'saldo-pedido-mixto',128.5,'QR') r`,[mixedOrder])).rows[0].r
 assert(orderPayment.cobro.pagoId)
 assert.equal(await balance(990002),128.5,'El cobro nuevo sigue propuesto hasta verificar')
 assert.equal(Number((await db.query('select pendiente from hermes.v_partida_estado where pedido_id=$1',[mixedOrder])).rows[0].pendiente),128.5)
 await claims(admin)
 await db.query(`select hermes.confirmar_pago($1,'admin@test.invalid')`,[orderPayment.cobro.pagoId])
 assert.equal(await balance(990002),0)
 assert.equal(Number((await db.query('select pendiente from hermes.v_partida_estado where pedido_id=$1',[mixedOrder])).rows[0].pendiente),0)
 await assert.rejects(()=>db.query(`select public.anular_pedido($1,'Prueba','admin@test.invalid')`,[mixedOrder]),/pagos confirmados/)
 await claims('00000000-0000-0000-0000-000000000003')
 await assert.rejects(()=>sale('saldo-test-inactivo'),/no autorizado/)
 await claims(caja)
 await db.exec(`grant usage on schema public,auth to authenticated;grant select,insert,update on public.venta,public.venta_linea,public.venta_pago,public.movimiento_caja,public.ubicacion,public.stock_actual,public.presentacion,public.sucursal,public.kardex_transacciones,public.perfil,public.sesion_caja to authenticated;grant usage,select on all sequences in schema public to authenticated;set role authenticated;`)
 assert.equal(Number((await available(990001)).disponible),2193,'Un cajero real sin acceso a Hermes puede consultar su cliente')
 await sale('saldo-test-rol-real',10,[],990001,10)
 await assert.rejects(()=>db.query(`update public.venta set saldo_favor_aplicado=999 where numero like 'VTA-%'`),/calculan en la operación/)
 await assert.rejects(()=>db.query(`update public.saldo_cliente_uso set monto=1`),/permission denied/)
 assert.equal((await db.query(`select has_function_privilege('anon','public.registrar_venta_con_saldo(jsonb,jsonb,bigint,bigint,numeric,numeric,text,text)','execute') ok`)).rows[0].ok,false)
 await db.exec('reset role')
 await claims(admin)
 await db.exec(`insert into public.cliente(id,nombre,tipo_precio,activo) values(990005,'Apertura deudora sintética','mayorista',true);
 insert into hermes.movimiento_cuenta(cliente_id,tipo,monto,idempotencia_clave,fecha_efectiva,creado_por)
 select id,'SALDO_APERTURA',100,'saldo-apertura-deudora',current_date,'prueba' from hermes.cliente where pos_cliente_id=990005;`)
 const deposit=(await db.query(`select public.registrar_cobro_cation(p_cliente_id=>990005,p_monto=>150,p_metodo=>'EFECTIVO',p_sesion_id=>900001,p_idempotencia=>'saldo-deposito-apertura',p_no_imputar=>true) r`)).rows[0].r
 await db.query(`select hermes.confirmar_pago($1,'admin@test.invalid')`,[deposit.pagoId])
 const legacyOrder=(await db.query(`insert into public.pedido(categoria,cliente_id,total,subtotal,numero) values('MAYOR',990005,100,100,'SALDO-APERTURA-PENDIENTE') returning id`)).rows[0].id
 await claims(caja)
 assert.equal(Number((await available(990005,legacyOrder)).disponible),50,'La apertura deudora ya consume 100 del depósito de 150; solo quedan 50 para el pedido')
 await assert.rejects(()=>db.query(`select public.aplicar_saldo_pedido($1,60,900001,'saldo-apertura-exceso')`,[legacyOrder]),/saldo disponible cambió/)
 await db.query(`select public.aplicar_saldo_pedido($1,50,900001,'saldo-apertura-pedido')`,[legacyOrder])
 assert.equal(Number((await available(990005,legacyOrder)).disponible),0)
 await db.exec(`update public.sesion_caja set cajero_id='00000000-0000-0000-0000-000000000001' where id=900001;`)
 await assert.rejects(()=>sale('saldo-turno-ajeno',1,[],990001,1),/propio turno/)
 await db.exec(`update public.sesion_caja set cajero_id='${caja}',estado='CERRADA' where id=900001;`)
 assert.equal((await sale('saldo-test-rol-real',10,[],990001,10)).rows[0].r.venta_id != null,true,'El reintento de una venta existente es válido tras cerrar el turno')
 await assert.rejects(()=>sale('saldo-turno-cerrado',1,[],990001,1),/cerrada|ABIERTA|abierta/)
 console.log('OK: saldo de apertura, mezcla, caja real, aplicaciones de pedido, idempotencia, rollback, stock, reversión y cajero sin acceso a Hermes')
}
