import assert from 'node:assert/strict'
import fs from 'node:fs/promises'

// Se ejecuta en el PostgreSQL aislado del conjunto de integración. Sin datos reales.
export async function testSincronizacionAutomatica(db, claims) {
  const snapshot = async () => (await db.query(`select
    (select count(*)::int from hermes.partida_abierta) partidas,
    (select count(*)::int from hermes.movimiento_cuenta) movimientos,
    (select sum(monto) from hermes.movimiento_cuenta) saldo`)).rows[0]
  const before = await snapshot()
  await db.exec(await fs.readFile(new URL('../migrations/20261003213326_hermes_clientes_pedidos_automaticos.sql', import.meta.url), 'utf8'))
  await db.exec(await fs.readFile(new URL('../migrations/20261003214031_hermes_vistas_sincronizacion_invocador.sql', import.meta.url), 'utf8'))
  const views = (await db.query(`select relname,reloptions from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='hermes' and relname in ('v_clientes_cation_pendientes','v_pedidos_cation_pendientes')`)).rows
  assert.equal(views.length,2)
  assert(views.every(v=>v.reloptions.includes('security_invoker=true')),'Las vistas respetan los permisos y RLS de quien consulta')
  assert.deepEqual(await snapshot(), before, 'La instalación no abre deudas históricas')
  // Completa el esquema reducido con las columnas usadas por la RPC vigente.
  await db.exec(`alter table public.pedido_linea
    alter column id add generated by default as identity,
    add column producto_id bigint,add column sucursal_origen_id bigint,
    add column es_personalizado boolean,add column descripcion text,
    add column unidad_medida text,add column nota text,add column presentacion_id bigint,
    add column cantidad_presentacion numeric,add column precio_lista numeric,add column descuento_pct numeric;
    create table public.presentacion(id bigint,producto_id bigint,factor_unidad_base numeric);`)
  await db.exec(await fs.readFile(new URL('./crear-pedido.fixture.sql',import.meta.url),'utf8'))
  await claims('00000000-0000-0000-0000-000000000002')
  const legacy = (await db.query(`select public.registrar_cobro_hermes(p_cliente_id=>900001,p_monto=>25,p_metodo=>'EFECTIVO',p_sesion_id=>900001,p_idempotencia=>'test-cobro-1') result`)).rows[0].result
  assert.equal(legacy.movementId,(await db.query(`select id from public.movimiento_caja where idempotencia_clave='test-cobro-1'`)).rows[0].id,'Las cajas anteriores pueden reintentar cobros registrados antes de la actualización')
  for (const [id, tipo, categoria] of [[900500,'mayorista','MAYORISTA'],[900501,'institucion','INSTITUCIONAL'],[900502,'corporativo','CORPORATIVO']]) {
    await db.query(`insert into public.cliente(id,nombre,tipo_precio,activo) values($1,'Cliente automático',$2,true)`, [id,tipo])
    const c = (await db.query('select id,categoria from hermes.cliente where pos_cliente_id=$1',[id])).rows[0]
    assert.equal(c.categoria,categoria,'El cliente aparece antes de tener pedidos')
    assert((await db.query('select 1 from hermes.cliente_credito where cliente_id=$1',[c.id])).rows[0])
    await db.query(`insert into public.pedido(id,categoria,cliente_id,total,subtotal,numero) values($1,'MAYOR',$2,125,125,$3)`, [id,id,`AUTO-${id}`])
    const part = (await db.query('select id,cliente_id,total from hermes.partida_abierta where pedido_id=$1',[id])).rows[0]
    assert.equal(part.cliente_id,c.id)
    assert.equal(Number(part.total),125)
    await db.query('select hermes.sincronizar_pedido_pos($1)',[id])
    await db.query(`update public.pedido set estado='COMPLETADO',recibido_en='2026-10-03T15:00:00Z' where id=$1`,[id])
    assert.equal((await db.query('select count(*)::int n from hermes.partida_abierta where pedido_id=$1',[id])).rows[0].n,1)
    assert.equal((await db.query(`select count(*)::int n from hermes.movimiento_cuenta where partida_id=$1 and tipo='CARGO'`,[part.id])).rows[0].n,1,'No cobra dos veces al completar')
  }
  await db.exec(`insert into public.cliente(id,nombre,tipo_precio,activo) values(900503,'Retail excluido','retail',true);
    insert into public.pedido(id,categoria,cliente_id,total,subtotal,numero) values(900503,'MAYOR',900503,50,50,'AUTO-RETAIL');
    update public.pedido set estado='COMPLETADO' where id=900503;`)
  assert.equal((await db.query('select count(*)::int n from hermes.cliente where pos_cliente_id=900503')).rows[0].n,0)
  assert.equal((await db.query('select count(*)::int n from hermes.partida_abierta where pedido_id=900503')).rows[0].n,0,'La categoría del pedido no convierte un retail en mayorista')
  assert.equal((await db.query('select count(*)::int n from hermes.v_pedidos_cation_pendientes where pedido_id=900503')).rows[0].n,0)
  assert.equal((await db.query('select count(*)::int n from hermes.v_clientes_cation_pendientes where id=900503')).rows[0].n,0)

  // Cabecera primero, total definitivo al terminar la RPC: la apertura espera al commit.
  await db.exec('begin')
  await db.exec(`insert into public.pedido(id,categoria,cliente_id,total,subtotal,numero) values(900504,'MAYOR',900500,0,0,'AUTO-FINAL');
    update public.pedido set total=300,subtotal=300 where id=900504;
    update public.pedido set total=280,subtotal=280 where id=900504;`)
  assert.equal((await db.query('select count(*)::int n from hermes.partida_abierta where pedido_id=900504')).rows[0].n,0)
  await db.exec('commit')
  assert.equal(Number((await db.query('select total from hermes.partida_abierta where pedido_id=900504')).rows[0].total),280)

  // Pedido sin cliente o precio: se vincula cuando los datos quedan completos.
  await db.exec(`insert into public.pedido(id,categoria,total,subtotal,numero) values(900505,'MAYOR',60,60,'AUTO-SIN-CLIENTE');
    insert into public.pedido(id,categoria,cliente_id,total,subtotal,numero) values(900506,'MAYOR',900500,null,null,'AUTO-SIN-PRECIO');`)
  assert.equal((await db.query('select count(*)::int n from hermes.partida_abierta where pedido_id in (900505,900506)')).rows[0].n,0)
  await db.exec('update public.pedido set cliente_id=900500 where id=900505; update public.pedido set total=60,subtotal=60 where id=900506;')
  assert.equal((await db.query('select count(*)::int n from hermes.partida_abierta where pedido_id in (900505,900506)')).rows[0].n,2)

  const lines = [{es_personalizado:true,descripcion:'Servicio de prueba',cantidad_base:2,precio_unitario:50}]
  const order = (await db.query(`select public.crear_pedido(p_categoria=>'MAYOR',p_referencia=>'RPC automática',p_lineas=>$1,p_cliente_id=>900500,p_descuento_general=>5) id`,[JSON.stringify(lines)])).rows[0].id
  assert.equal(Number((await db.query('select total from hermes.partida_abierta where pedido_id=$1',[order])).rows[0].total),95,'La RPC real sincroniza su total después del descuento')
  const afterRpc = await snapshot()
  await assert.rejects(()=>db.query(`select public.crear_pedido(p_categoria=>'MAYOR',p_referencia=>'RPC inválida',p_lineas=>$1,p_cliente_id=>900500)`,[JSON.stringify([{...lines[0],cantidad_base:-1}])]),/cantidad debe ser positiva/)
  assert.deepEqual(await snapshot(),afterRpc,'Un pedido inválido no deja un cargo o partida huérfanos')

  await db.exec(`begin; insert into public.pedido(id,categoria,cliente_id,total,subtotal,numero) values(900507,'MAYOR',900500,70,70,'AUTO-CANCELADO');
    update public.pedido set estado='CANCELADO' where id=900507; commit;`)
  assert.equal((await db.query('select count(*)::int n from hermes.partida_abierta where pedido_id=900507')).rows[0].n,0,'Un pedido cancelado dentro del guardado no genera deuda')

  // Un cajero no requiere permiso de ejecución de las funciones internas del conciliador.
  await db.exec(`grant select,insert,update on public.cliente,public.pedido to authenticated;
    grant usage on schema public to authenticated;
    set role authenticated;
    insert into public.cliente(id,nombre,tipo_precio,activo) values(900508,'Cliente de cajero','corporativo',true);
    insert into public.pedido(id,categoria,cliente_id,total,subtotal,numero) values(900508,'CORPORATIVO',900508,40,40,'AUTO-CAJERO');
    reset role;`)
  assert.equal((await db.query('select count(*)::int n from hermes.partida_abierta where pedido_id=900508')).rows[0].n,1,'El evento funciona con el rol authenticated de un cajero')

  await db.exec(`insert into hermes.cliente(id,nombre,categoria) values(900509,'Cuenta manual con el mismo ID','CORPORATIVO');
    insert into public.cliente(id,nombre,tipo_precio,activo) values(900509,'Cliente con ID coincidente','corporativo',true);
    insert into public.pedido(id,categoria,cliente_id,total,subtotal,numero) values(900509,'CORPORATIVO',900509,40,40,'AUTO-ID');`)
  const mapped = (await db.query('select id from hermes.cliente where pos_cliente_id=900509')).rows[0].id
  assert.notEqual(mapped,900509)
  assert.equal((await db.query('select cliente_id from hermes.partida_abierta where pedido_id=900509')).rows[0].cliente_id,mapped,'Ancla al cliente POS correcto aunque Hermes use otro ID')

  await db.exec(`update hermes.cliente_credito set plazo_dias=75,limite_credito=9000 where cliente_id=900500;
    update public.cliente set nombre='Nombre nuevo',documento='NIT-AUTO' where id=900500;`)
  assert.equal((await db.query('select plazo_dias from hermes.cliente_credito where cliente_id=900500')).rows[0].plazo_dias,75)
  assert.equal((await db.query('select nombre from hermes.cliente where pos_cliente_id=900500')).rows[0].nombre,'Nombre nuevo')
  await db.exec(`update public.cliente set tipo_precio='retail' where id=900500`)
  assert.equal((await db.query('select activo from hermes.cliente where pos_cliente_id=900500')).rows[0].activo,false,'Al pasar a retail conserva el historial sin cuenta activa')
  await db.exec(`update public.cliente set tipo_precio='mayorista' where id=900500`)
  assert.equal((await db.query('select plazo_dias from hermes.cliente_credito where cliente_id=900500')).rows[0].plazo_dias,75)

  const retailCall = () => db.query(`select public.registrar_cobro_cation(p_cliente_id=>900503,p_monto=>10,p_metodo=>'EFECTIVO',p_sesion_id=>900001,p_idempotencia=>'auto-retail-cobro') result`)
  const retail = (await retailCall()).rows[0].result
  assert(retail.movementId)
  assert.equal(retail.pagoId,null)
  assert.equal(retail.excluidoRetail,true)
  assert.equal((await retailCall()).rows[0].result.movementId,retail.movementId,'El cobro retail conserva su idempotencia en caja')
  assert.equal((await db.query('select count(*)::int n from hermes.cliente where pos_cliente_id=900503')).rows[0].n,0,'Cobrar retail tampoco lo importa')
  const paid = (await db.query(`select public.registrar_cobro_cation(p_pedido_id=>900502,p_monto=>25,p_metodo=>'QR',p_sesion_id=>900001,p_idempotencia=>'auto-corporativo-cobro') result`)).rows[0].result
  assert(paid.pagoId)
  assert.equal((await db.query('select estado from hermes.pago where id=$1',[paid.pagoId])).rows[0].estado,'PROPUESTO','La sincronización no confirma pagos')
  assert.equal(Number((await db.query('select monto from hermes.pago_aplicacion where pago_id=$1',[paid.pagoId])).rows[0].monto),25)
  for (const role of ['anon','authenticated','service_role']) {
    assert.equal((await db.query(`select has_function_privilege($1,'hermes.al_guardar_pedido_pos()','EXECUTE') permitted`,[role])).rows[0].permitted,false)
    assert.equal((await db.query(`select has_function_privilege($1,'hermes.registrar_cobro_pos_interno(bigint,bigint,numeric,public.metodo_pago,bigint,text,boolean,jsonb,text,boolean)','EXECUTE') permitted`,[role])).rows[0].permitted,false)
  }
  assert.equal((await db.query(`select has_function_privilege('anon','public.registrar_cobro_cation(bigint,bigint,numeric,public.metodo_pago,bigint,text,boolean,jsonb,text)','EXECUTE') permitted`)).rows[0].permitted,false)
  console.log('OK: sincronización automática de las tres categorías, cliente primero, importe final, idempotencia, retail excluido, crédito y pagos preservados')
}
