import { CheckCircle2, PackageCheck, Truck, XCircle } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import type { OrderView, OrderWorkflowStatus } from '../../application/shared/models'
import { orderService } from '../../infrastructure/mock/services'
import { formatMoney, money } from '../../domain/common/money'
import { FeatureShell, FeatureState, FeatureToolbar, statusLabel } from '../shared/FeatureShell'
import { Modal } from '../../components/Modal'

export function OrdersPage({ notify }: { notify: (message: string) => void }) {
  const [orders, setOrders] = useState<OrderView[]>([])
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState<'all' | OrderWorkflowStatus>('all')
  const [selected, setSelected] = useState<OrderView | null>(null)
  const load = () => orderService.list().then(setOrders)
  useEffect(() => { void load() }, [])
  const filtered = useMemo(() => orders.filter((order) => (filter === 'all' || order.status === filter) && `${order.number} ${order.customerName}`.toLowerCase().includes(query.toLowerCase())), [orders, query, filter])
  const dispatch = async (order: OrderView) => { if (!confirm('¿Registrar un despacho parcial simulado? No modificará inventario.')) return; const result = await orderService.partialDispatch(order.id); setSelected(result); await load(); notify('Despacho parcial simulado') }
  const cancel = async (order: OrderView) => { if (!confirm(`¿Cancelar ${order.number}? Esta acción solo afecta datos mock.`)) return; const updated = { ...order, status: 'cancelled' as const, events: [...order.events, { at: new Date().toLocaleString('es-BO'), label: 'Pedido cancelado', detail: 'Sin movimientos reales de inventario' }] }; await orderService.save(updated); setSelected(updated); await load(); notify('Pedido cancelado') }
  return <FeatureShell eyebrow="OPERACIONES" title="Pedidos" subtitle="Reserva, preparación y despacho simulado"><FeatureToolbar query={query} onQuery={setQuery} placeholder="Buscar por pedido o cliente..."><select value={filter} onChange={(e) => setFilter(e.target.value as typeof filter)}><option value="all">Todos los estados</option>{['draft','confirmed','awaiting_stock','reserved','preparing','ready','dispatched','delivered','cancelled'].map((value) => <option key={value} value={value}>{statusLabel[value]}</option>)}</select></FeatureToolbar>{!filtered.length ? <FeatureState type={orders.length ? 'no-results' : 'empty'} text="No hay pedidos" /> : <div className="order-grid">{filtered.map((order) => { const requested = order.lines.reduce((sum,line)=>sum+line.quantity,0); const prepared=order.lines.reduce((sum,line)=>sum+line.prepared,0); return <button key={order.id} className="order-card" onClick={() => setSelected(order)}><header><div><strong>{order.number}</strong><span>{order.customerName}</span></div><i className={`status-chip ${order.status}`}>{statusLabel[order.status]}</i></header><div className="progress"><span style={{width:`${requested ? prepared/requested*100 : 0}%`}} /></div><div><span>{prepared} preparadas</span><span>{requested-prepared} pendientes</span></div><footer><span>{order.channel}</span><strong>{formatMoney(money(order.lines.reduce((sum,line)=>sum+line.unitPriceCents*line.quantity,0)))}</strong></footer></button>})}</div>}{selected && <Modal title={selected.number} subtitle={selected.customerName} onClose={() => setSelected(null)} wide><div className="modal-body order-detail"><div className="order-status-line"><PackageCheck /><div><span>Estado actual</span><strong>{statusLabel[selected.status]}</strong></div></div>{selected.lines.map((line) => <article key={line.id}><header><div><strong>{line.name}</strong><small>{line.sku}</small></div><span>{line.prepared}/{line.quantity} preparadas</span></header><div className="allocation-bars">{line.allocations.map((allocation) => <div key={allocation.location}><span>{allocation.location}</span><b>{allocation.quantity} uds.</b></div>)}</div></article>)}<h3>Historial</h3><div className="timeline">{selected.events.map((event,index) => <div key={`${event.at}-${index}`}><CheckCircle2 /><span><strong>{event.label}</strong><small>{event.at} · {event.detail}</small></span></div>)}</div></div><footer className="modal-actions"><button className="secondary-button" onClick={()=>window.print()}>Pedido A4</button><button className="secondary-button" onClick={()=>window.print()}>Nota de entrega A4</button><button className="danger-button" disabled={['delivered','cancelled'].includes(selected.status)} onClick={() => cancel(selected)}><XCircle /> Cancelar</button><button className="primary-button" disabled={!['preparing','ready'].includes(selected.status)} onClick={() => dispatch(selected)}><Truck /> Despacho parcial</button></footer></Modal>}</FeatureShell>
}
