-- Consumo trazable de dinero confirmado. No convierte propuestas en fondos disponibles.
alter table public.venta add column cliente_acreedor boolean not null default false;
alter table public.venta add column saldo_cliente_antes numeric(14,2);
alter table public.venta add column saldo_favor_aplicado numeric(14,2) not null default 0;

create table public.saldo_cliente_uso (
 id bigint generated by default as identity primary key,
 cliente_id bigint not null references public.cliente(id),
 hermes_cliente_id bigint not null references hermes.cliente(id),
 venta_id bigint references public.venta(id),
 pedido_id bigint references public.pedido(id),
 sesion_caja_id bigint not null references public.sesion_caja(id),
 monto numeric(14,2) not null check (monto>0),
 saldo_antes numeric(14,2) not null,
 saldo_despues numeric(14,2) not null,
 idempotencia_clave text not null unique,
 solicitud jsonb not null,
 creado_por text not null,
 creado_por_id uuid,
 creado_en timestamptz not null default now(),
 anulado_en timestamptz,
 motivo_anulacion text,
 movimiento_id bigint references hermes.movimiento_cuenta(id),
 reversion_id bigint references hermes.movimiento_cuenta(id),
 check (num_nonnulls(venta_id,pedido_id)=1)
);
create unique index saldo_uso_venta_unica on public.saldo_cliente_uso(venta_id) where venta_id is not null;
create index saldo_uso_turno on public.saldo_cliente_uso(sesion_caja_id,creado_en desc);
create index saldo_uso_cliente on public.saldo_cliente_uso(hermes_cliente_id);
create index saldo_uso_cliente_pos on public.saldo_cliente_uso(cliente_id);
create index saldo_uso_movimiento on public.saldo_cliente_uso(movimiento_id) where movimiento_id is not null;
create index saldo_uso_reversion on public.saldo_cliente_uso(reversion_id) where reversion_id is not null;
create index saldo_uso_pedido on public.saldo_cliente_uso(pedido_id) where pedido_id is not null;
alter table public.saldo_cliente_uso enable row level security;
revoke all on public.saldo_cliente_uso from public,anon,authenticated,service_role;
grant select,insert on public.saldo_cliente_uso to authenticated;
grant select on public.saldo_cliente_uso to hermes_app;
grant usage,select on sequence public.saldo_cliente_uso_id_seq to authenticated;
create policy saldo_uso_operador on public.saldo_cliente_uso for select to authenticated using (
 exists(select 1 from public.perfil p where p.id=(select auth.uid()) and p.activo and
 (p.rol in ('admin','gerente') or (p.rol='cajero' and exists(select 1 from public.sesion_caja s where s.id=sesion_caja_id and s.cajero_id=p.id))))
);
create policy saldo_uso_registro on public.saldo_cliente_uso for insert to authenticated with check (
 creado_por_id=(select auth.uid()) and exists(select 1 from public.perfil p where p.id=(select auth.uid()) and p.activo and
 (p.rol in ('admin','gerente') or (p.rol='cajero' and exists(select 1 from public.sesion_caja s where s.id=sesion_caja_id and s.cajero_id=p.id))))
);
create policy saldo_uso_hermes on public.saldo_cliente_uso for select to hermes_app using (true);

create table hermes.saldo_uso_fuente (
 uso_id bigint not null references public.saldo_cliente_uso(id) deferrable initially deferred,
 movimiento_id bigint not null references hermes.movimiento_cuenta(id),
 monto numeric(14,2) not null check(monto>0),primary key(uso_id,movimiento_id)
);
create index saldo_fuente_movimiento on hermes.saldo_uso_fuente(movimiento_id);
create table hermes.saldo_uso_partida (
 uso_id bigint not null references public.saldo_cliente_uso(id) deferrable initially deferred,
 partida_id bigint not null references hermes.partida_abierta(id),
 monto numeric(14,2) not null check(monto>0),primary key(uso_id,partida_id)
);
create index saldo_uso_partida_destino on hermes.saldo_uso_partida(partida_id);
alter table hermes.saldo_uso_fuente enable row level security;
alter table hermes.saldo_uso_partida enable row level security;
revoke all on hermes.saldo_uso_fuente,hermes.saldo_uso_partida from public,anon,authenticated,service_role;
grant select on hermes.saldo_uso_fuente,hermes.saldo_uso_partida to hermes_app,authenticated;
create policy saldo_fuente_lectura on hermes.saldo_uso_fuente for select to authenticated using (public.hermes_tiene_acceso());
create policy saldo_partida_lectura on hermes.saldo_uso_partida for select to authenticated using (public.hermes_tiene_acceso());
create policy saldo_fuente_interna on hermes.saldo_uso_fuente for select to hermes_app using (true);
create policy saldo_partida_interna on hermes.saldo_uso_partida for select to hermes_app using (true);

-- Pool de orígenes: apertura acreedora y dinero/ajustes confirmados todavía sin consumir.
-- Las contrapartidas de anulación no son fondos nuevos: se libera el origen original.
create function hermes.fuentes_saldo_disponible(p_cliente_id bigint)
returns table(movimiento_id bigint,disponible numeric) language sql stable security definer
set search_path=pg_catalog,hermes,public as $$
 with cargos_previos as (
  select coalesce(sum(m.monto),0) monto from hermes.movimiento_cuenta m
  where m.cliente_id=p_cliente_id and m.monto>0 and m.partida_id is null
  and m.tipo::text in ('SALDO_APERTURA','AJUSTE','CARGO')
  and not exists(select 1 from public.saldo_cliente_uso s where s.movimiento_id=m.id)
 ), fuentes as (
 select m.id,m.fecha_efectiva,greatest(-m.monto-coalesce(u.aplicado,0),0) fondo
 from hermes.movimiento_cuenta m
 left join lateral(select sum(f.monto) aplicado from hermes.saldo_uso_fuente f
   join public.saldo_cliente_uso s on s.id=f.uso_id where f.movimiento_id=m.id and s.anulado_en is null) u on true
 where m.cliente_id=p_cliente_id and m.monto<0 and m.tipo::text in ('SALDO_APERTURA','ANTICIPO','NOTA_CREDITO','AJUSTE')
 and coalesce(m.idempotencia_clave,'') not like 'anulacion-partida-%'
 and not exists(select 1 from public.saldo_cliente_uso s where s.reversion_id=m.id)
 and (m.pago_id is null or exists(select 1 from hermes.pago p where p.id=m.pago_id and p.estado::text in ('CONFIRMADO','ACREDITADO')))
 ), ordenadas as (
  select *,coalesce(sum(fondo) over(order by fecha_efectiva,id rows between unbounded preceding and 1 preceding),0) anterior from fuentes
 )
 select id,greatest(fondo-greatest((select monto from cargos_previos)-anterior,0),0) from ordenadas order by fecha_efectiva,id
$$;
revoke all on function hermes.fuentes_saldo_disponible(bigint) from public,anon,authenticated,service_role;

create function public.consultar_saldo_disponible(p_cliente_id bigint,p_pedido_id bigint default null)
returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public,hermes as $$
declare cid bigint; saldo numeric; fondos numeric; pendiente numeric:=0; revision numeric;
begin
 perform hermes.exigir_operador_pos();
 if not exists(select 1 from public.cliente where id=p_cliente_id and activo and tipo_precio::text in ('mayorista','institucion','corporativo')) then
   return jsonb_build_object('sinCuenta',true,'disponible',0); end if;
 select id into cid from hermes.cliente where pos_cliente_id=p_cliente_id and activo;
 if cid is null then return jsonb_build_object('sinCuenta',true,'disponible',0); end if;
 select saldo_confirmado,monto_en_revision into saldo,revision from hermes.v_saldo_cliente where cliente_id=cid;
 select coalesce(sum(disponible),0) into fondos from hermes.fuentes_saldo_disponible(cid);
 if p_pedido_id is not null then
  if not exists(select 1 from public.pedido where id=p_pedido_id and cliente_id=p_cliente_id and estado::text in ('ABIERTO','COMPLETADO')) then raise exception 'El pedido no pertenece al cliente o está anulado'; end if;
  select coalesce(sum(greatest(ve.pendiente-ve.en_revision,0)),0) into pendiente from hermes.v_partida_estado ve where pedido_id=p_pedido_id and cliente_id=cid and estado::text='ABIERTA';
  fondos:=least(fondos,pendiente);
 else fondos:=least(fondos,greatest(-coalesce(saldo,0),0)); end if;
 return jsonb_build_object('sinCuenta',false,'saldoConfirmado',coalesce(saldo,0),'disponible',fondos,'enRevision',coalesce(revision,0),'pedidoPendiente',pendiente,'aplicadoPedido',(select coalesce(sum(monto),0) from public.saldo_cliente_uso where pedido_id=p_pedido_id and anulado_en is null),'esAcreedor',coalesce(saldo,0)<0);
end $$;
revoke all on function public.consultar_saldo_disponible(bigint,bigint) from public,anon;
grant execute on function public.consultar_saldo_disponible(bigint,bigint) to authenticated;

create function hermes.marcar_venta_acreedora() returns trigger language plpgsql security definer set search_path=pg_catalog,public,hermes as $$
declare cid bigint;
begin
 new.cliente_acreedor:=false;new.saldo_cliente_antes:=null;new.saldo_favor_aplicado:=0;
 if new.cliente_id is not null and exists(select 1 from public.cliente where id=new.cliente_id and activo and tipo_precio::text in ('mayorista','institucion','corporativo')) then
  select id into cid from hermes.cliente where pos_cliente_id=new.cliente_id and activo for update;
  if cid is not null then
   select coalesce(sum(monto),0) into new.saldo_cliente_antes from hermes.movimiento_cuenta where cliente_id=cid;
   new.cliente_acreedor:=new.saldo_cliente_antes<0;
  end if;
 end if;
 return new;
end $$;
revoke all on function hermes.marcar_venta_acreedora() from public,anon,authenticated,service_role;
create trigger saldo_marcar_venta before insert on public.venta for each row execute function hermes.marcar_venta_acreedora();

create function hermes.registrar_uso_saldo() returns trigger language plpgsql security definer set search_path=pg_catalog,public,hermes as $$
declare cid bigint; saldo numeric; fondos numeric; pendiente numeric; restante numeric; tomado numeric; r record; v public.venta%rowtype; s public.sesion_caja%rowtype; actor public.perfil%rowtype;
begin
 perform hermes.exigir_operador_pos();
 select * into actor from public.perfil where id=auth.uid() and activo and rol in ('cajero','admin','gerente');
 if not found then raise exception 'Se requiere un operador activo para usar saldo' using errcode='42501';end if;
 select * into s from public.sesion_caja where id=new.sesion_caja_id for share;
 if not found or s.estado::text<>'ABIERTA' then raise exception 'La caja está cerrada';end if;
 if actor.rol='cajero' and s.cajero_id is distinct from actor.id then raise exception 'Solo puedes operar en tu propio turno' using errcode='42501';end if;
 if new.idempotencia_clave is null or length(btrim(new.idempotencia_clave))<1 or length(new.idempotencia_clave)>200 then raise exception 'Clave de operación inválida';end if;
 if new.monto is null or new.monto<=0 or new.monto::text in ('NaN','Infinity','-Infinity') then raise exception 'Importe de saldo inválido';end if;
 if not exists(select 1 from public.cliente where id=new.cliente_id and activo and tipo_precio::text in ('mayorista','institucion','corporativo')) then raise exception 'El saldo solo aplica a clientes mayoristas, institucionales y corporativos';end if;
 select id into cid from hermes.cliente where pos_cliente_id=new.cliente_id and activo for update;
 if cid is null then raise exception 'El cliente no tiene cuenta activa en el conciliador';end if;
 new.hermes_cliente_id:=cid;new.creado_por_id:=actor.id;new.creado_por:=coalesce(actor.email,actor.id::text);new.creado_en:=now();new.anulado_en:=null;new.motivo_anulacion:=null;new.reversion_id:=null;new.movimiento_id:=null;
 select coalesce(sum(monto),0) into saldo from hermes.movimiento_cuenta where cliente_id=cid;
 new.saldo_antes:=saldo;
 select coalesce(sum(disponible),0) into fondos from hermes.fuentes_saldo_disponible(cid);
 if new.venta_id is not null then
  select * into v from public.venta where id=new.venta_id for update;
  if not found or v.estado::text<>'ABIERTA' or v.cliente_id is distinct from new.cliente_id or v.sesion_caja_id is distinct from new.sesion_caja_id or v.numero not like 'VTA-%' then raise exception 'La venta no admite esta aplicación de saldo';end if;
  fondos:=least(fondos,greatest(-saldo,0));
  if new.monto+coalesce((select sum(monto) from public.venta_pago where venta_id=new.venta_id),0)>v.total then raise exception 'El saldo aplicado supera el pendiente de la venta';end if;
 else
  if not exists(select 1 from public.pedido where id=new.pedido_id and cliente_id=new.cliente_id and estado::text in ('ABIERTO','COMPLETADO')) then raise exception 'Pedido inválido o anulado';end if;
  perform 1 from hermes.partida_abierta where cliente_id=cid order by id for update;
  select coalesce(sum(greatest(ve.pendiente-ve.en_revision,0)),0) into pendiente from hermes.v_partida_estado ve where pedido_id=new.pedido_id and cliente_id=cid and estado::text='ABIERTA';
  if new.monto+coalesce((new.solicitud->>'nuevo')::numeric,0)>pendiente then raise exception 'El saldo y el dinero nuevo superan el pendiente vigente';end if;
  fondos:=least(fondos,pendiente);
 end if;
 if new.monto>fondos then raise exception 'El saldo disponible cambió: puedes aplicar hasta Bs %. Actualiza antes de confirmar.',fondos;end if;
 restante:=new.monto;
 for r in select * from hermes.fuentes_saldo_disponible(cid) loop
  exit when restante<=0;
  tomado:=least(restante,r.disponible);
  if tomado>0 then insert into hermes.saldo_uso_fuente(uso_id,movimiento_id,monto) values(new.id,r.movimiento_id,tomado);restante:=restante-tomado;end if;
 end loop;
 if restante<>0 then raise exception 'No se pudo reservar el saldo confirmado';end if;
 if new.venta_id is not null then
  insert into hermes.movimiento_cuenta(cliente_id,tipo,monto,idempotencia_clave,fecha_efectiva,referencia,motivo,creado_por)
  values(cid,'CARGO',new.monto,'saldo-venta-'||new.venta_id,(now() at time zone 'America/La_Paz')::date,v.numero,'Compra cubierta con saldo a favor',new.creado_por) returning id into new.movimiento_id;
  update public.venta set saldo_favor_aplicado=new.monto,cliente_acreedor=saldo<0,saldo_cliente_antes=saldo where id=new.venta_id;
  new.saldo_despues:=saldo+new.monto;
 else
  restante:=new.monto;
  for r in select ve.partida_id,greatest(ve.pendiente-ve.en_revision,0) disponible from hermes.v_partida_estado ve where pedido_id=new.pedido_id and cliente_id=cid and estado::text='ABIERTA' order by creado_en,partida_id loop
   exit when restante<=0;tomado:=least(restante,r.disponible);
   if tomado>0 then insert into hermes.saldo_uso_partida(uso_id,partida_id,monto) values(new.id,r.partida_id,tomado);restante:=restante-tomado;end if;
  end loop;
  if restante<>0 then raise exception 'El pendiente del pedido cambió';end if;
  -- El cargo del pedido ya redujo el saldo de cuenta. Aplicar no vuelve a descontarlo.
  new.saldo_despues:=saldo;
 end if;
 return new;
end $$;
revoke all on function hermes.registrar_uso_saldo() from public,anon,authenticated,service_role;
create trigger saldo_registrar_uso before insert on public.saldo_cliente_uso for each row execute function hermes.registrar_uso_saldo();

create function hermes.cerrar_partidas_con_saldo() returns trigger language plpgsql security definer set search_path=pg_catalog,hermes,public as $$
begin
 if new.pedido_id is not null then
  update hermes.partida_abierta pa set estado='PAGADA' from hermes.v_partida_estado ve
   where ve.partida_id=pa.id and pa.pedido_id=new.pedido_id and pa.estado::text='ABIERTA' and ve.pendiente<=0;
 end if;return new;
end $$;
revoke all on function hermes.cerrar_partidas_con_saldo() from public,anon,authenticated,service_role;
create trigger saldo_cerrar_partidas after insert on public.saldo_cliente_uso for each row execute function hermes.cerrar_partidas_con_saldo();

create function public.aplicar_saldo_pedido(p_pedido_id bigint,p_monto numeric,p_sesion_caja_id bigint,p_idempotencia text,p_monto_nuevo numeric default 0,p_metodo public.metodo_pago default 'EFECTIVO')
returns jsonb language plpgsql set search_path=pg_catalog,public as $$
 declare cid bigint; previo public.saldo_cliente_uso%rowtype; uso public.saldo_cliente_uso%rowtype; cobro jsonb; intento jsonb;
begin
 if p_monto is null or p_monto<=0 or p_monto_nuevo is null or p_monto_nuevo<0 or p_monto::text in ('NaN','Infinity','-Infinity') or p_monto_nuevo::text in ('NaN','Infinity','-Infinity') then raise exception 'Importes inválidos';end if;
 if p_idempotencia is null or length(btrim(p_idempotencia))<1 or length(p_idempotencia)>180 then raise exception 'Clave de operación inválida';end if;
 select cliente_id into cid from public.pedido where id=p_pedido_id;
 intento:=jsonb_build_object('pedido',p_pedido_id,'sesion',p_sesion_caja_id,'monto',round(p_monto,2),'nuevo',round(p_monto_nuevo,2),'metodo',p_metodo);
 perform pg_advisory_xact_lock(hashtextextended('saldo-pedido:'||p_idempotencia,0));
 select * into previo from public.saldo_cliente_uso where idempotencia_clave=p_idempotencia;
 if found then
  if previo.solicitud<>intento or previo.anulado_en is not null then raise exception 'Esta clave ya corresponde a otra operación o está anulada';end if;
  return jsonb_build_object('usoId',previo.id,'saldoAplicado',previo.monto,'saldoRestante',greatest(-previo.saldo_despues,0),'reintento',true);
 end if;
 if p_monto+p_monto_nuevo>(public.consultar_saldo_disponible(cid,p_pedido_id)->>'pedidoPendiente')::numeric then raise exception 'El saldo y el dinero nuevo superan el pendiente del pedido';end if;
 insert into public.saldo_cliente_uso(cliente_id,hermes_cliente_id,pedido_id,sesion_caja_id,monto,saldo_antes,saldo_despues,idempotencia_clave,solicitud,creado_por)
 values(cid,0,p_pedido_id,p_sesion_caja_id,p_monto,0,0,p_idempotencia,intento,'') returning * into uso;
 if p_monto_nuevo>0 then
  cobro:=public.registrar_cobro_cation(p_pedido_id=>p_pedido_id,p_monto=>p_monto_nuevo,p_metodo=>p_metodo,p_sesion_id=>p_sesion_caja_id,p_idempotencia=>p_idempotencia||':nuevo');
 end if;
 return jsonb_build_object('usoId',uso.id,'saldoAplicado',uso.monto,'saldoRestante',greatest(-uso.saldo_despues,0),'cobro',cobro,'reintento',false);
end $$;
revoke all on function public.aplicar_saldo_pedido(bigint,numeric,bigint,text,numeric,public.metodo_pago) from public,anon;
grant execute on function public.aplicar_saldo_pedido(bigint,numeric,bigint,text,numeric,public.metodo_pago) to authenticated;

create function hermes.revertir_saldo_venta() returns trigger language plpgsql security definer set search_path=pg_catalog,public,hermes as $$
declare u public.saldo_cliente_uso%rowtype; mid bigint;
begin
 select * into u from public.saldo_cliente_uso where venta_id=new.id and anulado_en is null;
 if not found then return new;end if;
 if not exists(select 1 from public.venta_evento where venta_id=new.id and accion='ANULADA') then raise exception 'Anula la venta mediante la operación oficial para devolver caja, stock y saldo juntos';end if;
 perform 1 from hermes.cliente where id=u.hermes_cliente_id for update;
 insert into hermes.movimiento_cuenta(cliente_id,tipo,monto,idempotencia_clave,fecha_efectiva,referencia,motivo,creado_por)
 values(u.hermes_cliente_id,'AJUSTE',-u.monto,'saldo-reversion-venta-'||new.id,(now() at time zone 'America/La_Paz')::date,new.numero,'Saldo devuelto por anulación de venta',coalesce(new.creado_por,'sistema')) returning id into mid;
 update public.saldo_cliente_uso set anulado_en=now(),motivo_anulacion='Venta anulada',reversion_id=mid where id=u.id;
 return new;
end $$;
revoke all on function hermes.revertir_saldo_venta() from public,anon,authenticated,service_role;
create trigger saldo_revertir_venta after update of estado on public.venta for each row when (new.estado::text='ANULADA' and old.estado is distinct from new.estado) execute function hermes.revertir_saldo_venta();

create function hermes.revertir_saldo_pedido() returns trigger language plpgsql security definer set search_path=pg_catalog,public,hermes as $$
declare cid bigint;r record;
begin
 if not exists(select 1 from public.saldo_cliente_uso where pedido_id=new.id and anulado_en is null) then return new;end if;
 if not public.app_es_admin() then raise exception 'Solo gerencia puede anular un pedido con saldo aplicado' using errcode='42501';end if;
 select id into cid from hermes.cliente where pos_cliente_id=new.cliente_id for update;
 perform 1 from hermes.partida_abierta where cliente_id=cid order by id for update;
 if exists(select 1 from hermes.pago_aplicacion a join hermes.pago p on p.id=a.pago_id join hermes.partida_abierta pa on pa.id=a.partida_id where pa.pedido_id=new.id and p.estado::text in ('CONFIRMADO','ACREDITADO')) then raise exception 'El pedido tiene pagos confirmados: revisa su reversión antes de anular';end if;
 if exists(select 1 from hermes.pago_aplicacion a join hermes.pago p on p.id=a.pago_id join hermes.partida_abierta pa on pa.id=a.partida_id where pa.pedido_id=new.id and p.estado::text='PROPUESTO') then raise exception 'El pedido tiene pagos por verificar: resuélvelos antes de anular';end if;
 update public.saldo_cliente_uso set anulado_en=now(),motivo_anulacion='Pedido anulado' where pedido_id=new.id and anulado_en is null;
 for r in select id,total,documento_interno from hermes.partida_abierta where pedido_id=new.id and estado::text in ('ABIERTA','PAGADA') order by id loop
  update hermes.partida_abierta set estado='ANULADA',anulada_en=now(),anulada_por=auth.uid()::text,motivo_anulacion='Pedido anulado; saldo aplicado restaurado' where id=r.id;
  insert into hermes.movimiento_cuenta(cliente_id,partida_id,tipo,monto,idempotencia_clave,fecha_efectiva,referencia,motivo,creado_por)
   values(cid,r.id,'NOTA_CREDITO',-r.total,'anulacion-partida-'||r.id,(now() at time zone 'America/La_Paz')::date,r.documento_interno,'Pedido anulado; saldo aplicado restaurado',auth.uid()::text);
 end loop;
 return new;
end $$;
revoke all on function hermes.revertir_saldo_pedido() from public,anon,authenticated,service_role;
create trigger saldo_revertir_pedido after update of estado on public.pedido for each row when(new.estado::text='CANCELADO' and old.estado is distinct from new.estado) execute function hermes.revertir_saldo_pedido();

create function hermes.proteger_saldo_venta() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$
begin
 if pg_trigger_depth()=1 and (new.cliente_acreedor is distinct from old.cliente_acreedor or new.saldo_cliente_antes is distinct from old.saldo_cliente_antes or new.saldo_favor_aplicado is distinct from old.saldo_favor_aplicado) then raise exception 'El estado y consumo de saldo se calculan en la operación de venta';end if;
 if new.estado::text='COMPLETADA' and new.numero like 'VTA-%' and new.saldo_favor_aplicado>0 and
  coalesce((select sum(monto) from public.venta_pago where venta_id=new.id),0)+coalesce((select sum(monto) from public.saldo_cliente_uso where venta_id=new.id and anulado_en is null),0)<>new.total then raise exception 'La venta no está cubierta por saldo y dinero nuevo';end if;
 return new;
end $$;
revoke all on function hermes.proteger_saldo_venta() from public,anon,authenticated,service_role;
create trigger saldo_proteger_venta before update on public.venta for each row execute function hermes.proteger_saldo_venta();

CREATE OR REPLACE FUNCTION public._registrar_venta_nucleo(p_lineas jsonb, p_pagos jsonb, p_sesion_caja_id bigint, p_cliente_id bigint, p_descuento_total numeric, p_usuario text, p_idempotencia text, p_forzar_reserva boolean, p_motivo_forzado text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO pg_catalog, public
AS $function$
declare
  v_venta_id bigint; v_header_ubic bigint; v_linea jsonb;
  v_prod bigint; v_cant numeric; v_cant_pres numeric; v_factor numeric;
  v_unit numeric; v_lista numeric; v_pres bigint; v_pres_base bigint;
  v_forzada bigint; v_st_forzada numeric; v_st_tienda numeric; v_st_almacen numeric;
  v_suc bigint; v_nombre_suc text; v_restante numeric; v_toma numeric;
  v_primer_kid bigint; v_kid bigint; v_ub record;
  v_sub numeric; v_subtotal numeric := 0; v_total numeric; v_pagado numeric; v_pago jsonb;
  v_previa jsonb;
  v_libre boolean; v_ubic_sobregiro bigint;
  v_ix int := 0;
  v_vendible numeric; v_reserva_motivo text; v_exceso numeric;
  v_reservado numeric; -- fix 2026-09-27: LIBRE sin reserva no se bloquea
  -- Brief Caja-1: numeración propia VTA-2026-NNNNN (A1) y recibido/estado de
  -- verificación por pago (A2/A3).
  v_numero text; v_anio int;
  v_metodo metodo_pago; v_recibido numeric; v_estado_verif text;
begin
  if jsonb_typeof(p_lineas) <> 'array' or jsonb_array_length(p_lineas) = 0 then
    raise exception 'p_lineas debe ser un array no vacío';
  end if;
  if jsonb_typeof(p_pagos) <> 'array' or jsonb_array_length(p_pagos) = 0 then
    raise exception 'p_pagos debe ser un array no vacío';
  end if;

  if p_forzar_reserva and (p_motivo_forzado is null or btrim(p_motivo_forzado) = '') then
    raise exception 'El motivo es obligatorio para vender por encima de la reserva';
  end if;

  if p_idempotencia is not null then
    if btrim(p_idempotencia) = '' or length(p_idempotencia) > 200 then
      raise exception 'Clave de idempotencia inválida (vacía, en blanco, o mayor a 200 caracteres)';
    end if;
    perform pg_advisory_xact_lock(hashtextextended('venta:' || p_idempotencia, 0));
    select jsonb_build_object('venta_id', v.id, 'numero', v.numero, 'subtotal', v.subtotal,
             'descuento_total', v.descuento_total, 'total', v.total, 'reintento', true)
      into v_previa
      from venta v
     where v.idempotencia_clave = p_idempotencia;
    if v_previa is not null then
      if exists(select 1 from public.saldo_cliente_uso u where u.venta_id=(v_previa->>'venta_id')::bigint and
          (u.anulado_en is not null or u.solicitud<>jsonb_build_object('lineas',p_lineas,'pagos',p_pagos,'cliente',p_cliente_id,'sesion',p_sesion_caja_id,'descuento',coalesce(p_descuento_total,0)))) then
        raise exception 'La clave corresponde a una venta con datos distintos o anulada';
      end if;
      return v_previa;
    end if;
  end if;

  perform 1 from sesion_caja where id = p_sesion_caja_id and estado = 'ABIERTA';
  if not found then raise exception 'No hay una sesión de caja abierta (%).', p_sesion_caja_id; end if;

  select id into v_header_ubic from ubicacion where sucursal_id = 2 order by id limit 1;
  if v_header_ubic is null then select id into v_header_ubic from ubicacion order by id limit 1; end if;

  -- A1: numeración gap-free — se asigna en la MISMA transacción que la venta, así
  -- que un rollback más abajo (stock insuficiente, pago que no cuadra, etc.) también
  -- revierte el incremento del contador. Mismo patrón que abrir_venta (serie VTD).
  v_anio := extract(year from now() at time zone 'America/La_Paz')::int;
  v_numero := formato_numero('VTA', v_anio, siguiente_numero('VTA', v_anio));

  insert into venta (numero, cliente_id, ubicacion_id, estado, creado_por, sesion_caja_id, idempotencia_clave)
  values (v_numero, p_cliente_id, v_header_ubic, 'ABIERTA', p_usuario, p_sesion_caja_id, p_idempotencia)
  returning id into v_venta_id;

  for v_linea in select * from jsonb_array_elements(p_lineas) loop
    v_ix := v_ix + 1;

    -- 2026-09-29 (personalizados en venta): línea sin producto de catálogo. No toca
    -- stock ni kardex, no tiene presentación; solo suma al total de la venta.
    if coalesce((v_linea->>'es_personalizado')::boolean, false) then
      if nullif(btrim(v_linea->>'producto_id'), '') is not null then
        raise exception 'Una línea personalizada no puede traer producto_id';
      end if;
      if nullif(btrim(v_linea->>'descripcion'), '') is null then
        raise exception 'Línea personalizada sin descripción';
      end if;
      v_unit  := (v_linea->>'precio_unitario')::numeric;
      v_lista := coalesce((v_linea->>'precio_lista')::numeric, v_unit);
      v_cant  := coalesce((v_linea->>'cantidad_base')::numeric, (v_linea->>'cantidad')::numeric);
      if v_unit is null or v_unit <= 0 then
        raise exception 'La línea personalizada "%" no tiene precio', btrim(v_linea->>'descripcion');
      end if;
      if v_cant is null or v_cant <= 0 then raise exception 'cantidad debe ser positiva'; end if;
      insert into venta_linea (venta_id, producto_id, es_personalizado, descripcion, unidad_medida,
                               cantidad, cantidad_presentacion, precio_lista, precio_unitario)
      values (v_venta_id, null, true, btrim(v_linea->>'descripcion'),
              coalesce(nullif(upper(btrim(v_linea->>'unidad_medida')), ''), 'UNIDAD'),
              v_cant, v_cant, v_lista, v_unit);
      v_subtotal := v_subtotal + round(v_unit * v_cant, 2);
      continue;
    end if;

    v_prod  := (v_linea->>'producto_id')::bigint;
    v_unit  := (v_linea->>'precio_unitario')::numeric;
    v_lista := coalesce((v_linea->>'precio_lista')::numeric, v_unit);
    v_pres  := (v_linea->>'presentacion_id')::bigint;
    if v_prod is null or v_unit is null then
      raise exception 'Línea inválida (producto_id/precio_unitario)';
    end if;

    select id into v_pres_base from presentacion
     where producto_id = v_prod and es_base = true and coalesce(activo, true) = true limit 1;
    if v_pres_base is null then raise exception 'Producto % sin presentación base', v_prod; end if;

    if v_pres is not null then
      select factor_unidad_base into v_factor from presentacion
       where id = v_pres and producto_id = v_prod and coalesce(activo, true);
      if v_factor is null then
        raise exception 'La presentación % no pertenece al producto % (o está inactiva)', v_pres, v_prod;
      end if;
      v_cant_pres := (v_linea->>'cantidad_presentacion')::numeric;
      if v_cant_pres is null or v_cant_pres <= 0 then
        raise exception 'cantidad_presentacion debe ser positiva';
      end if;
      v_cant := v_cant_pres * v_factor;
    else
      v_pres := v_pres_base;
      v_cant := coalesce((v_linea->>'cantidad_base')::numeric, (v_linea->>'cantidad')::numeric);
      v_cant_pres := v_cant;
    end if;
    if v_cant is null or v_cant <= 0 then raise exception 'cantidad debe ser positiva'; end if;

    -- ── COMPUERTA 1: origen forzado por el POS ───────────────────────────────
    v_forzada := (v_linea->>'sucursal_origen_id')::bigint;
    if v_forzada is not null then
      v_libre := coalesce(permite_sobregiro_sucursal(v_prod, v_forzada), false);
      select coalesce(sum(sa.cantidad_base), 0) into v_st_forzada
        from stock_actual sa join ubicacion u on u.id = sa.ubicacion_id
       where sa.producto_id = v_prod and u.sucursal_id = v_forzada;
      if v_st_forzada < v_cant and not v_libre then
        select nombre into v_nombre_suc from sucursal where id = v_forzada;
        raise exception 'Stock insuficiente en % para el producto % (necesita %, hay %)',
          coalesce(v_nombre_suc, 'sucursal ' || v_forzada), v_prod, v_cant, v_st_forzada;
      end if;
      v_suc := v_forzada;
    else
      -- ── COMPUERTA 2: elección automática de sucursal ───────────────────────
      select coalesce(sum(sa.cantidad_base), 0) into v_st_tienda
        from stock_actual sa join ubicacion u on u.id = sa.ubicacion_id
       where sa.producto_id = v_prod and u.sucursal_id = 2;
      select coalesce(sum(sa.cantidad_base), 0) into v_st_almacen
        from stock_actual sa join ubicacion u on u.id = sa.ubicacion_id
       where sa.producto_id = v_prod and u.sucursal_id = 1;
      if v_st_tienda >= v_cant then v_suc := 2;
      elsif v_st_almacen >= v_cant then v_suc := 1;
      elsif coalesce(permite_sobregiro_sucursal(v_prod, 2), false) then
        v_suc := 2;
      else
        raise exception 'Stock insuficiente para producto % (necesita %, Tienda %, Almacén %)',
          v_prod, v_cant, v_st_tienda, v_st_almacen;
      end if;
      v_libre := coalesce(permite_sobregiro_sucursal(v_prod, v_suc), false);
    end if;

    -- ── COMPUERTA 2.5: protección de reservas ────────────────────────────────
    select vendible, reservado, motivo into v_vendible, v_reservado, v_reserva_motivo
      from saldo_vendible(array[v_prod], v_suc)
     limit 1;

    -- Fix 2026-09-27: en una sucursal LIBRE (Tienda en venta libre) sin stock contado,
    -- vendible = 0 aunque no haya NINGUNA reserva, y la compuerta bloqueaba toda venta
    -- con "está reservado" falso. Regla S10 intacta: si hay reserva real (reservado > 0),
    -- la reserva sigue ganando sobre LIBRE. Sin reserva, LIBRE vende.
    if v_cant > coalesce(v_vendible, 0)
       and not (coalesce(v_libre, false) and coalesce(v_reservado, 0) = 0) then
      v_exceso := v_cant - coalesce(v_vendible, 0);
      if not p_forzar_reserva then
        raise exception 'Producto % está reservado: % unidad(es) comprometidas para % en esta sucursal (vendible real: %)',
          v_prod, v_exceso, coalesce(v_reserva_motivo, 'otro pedido'), coalesce(v_vendible, 0)
          using errcode = 'check_violation';
      else
        insert into venta_sobre_reserva (venta_id, producto_id, cantidad_base, pedidos_afectados, motivo, usuario)
        values (v_venta_id, v_prod, v_exceso, v_reserva_motivo, p_motivo_forzado, p_usuario);
      end if;
    end if;

    -- ── COMPUERTA 3: reparto entre ubicaciones ───────────────────────────────
    v_restante := v_cant; v_primer_kid := null;
    for v_ub in
      select sa.ubicacion_id, sa.cantidad_base
        from stock_actual sa join ubicacion u on u.id = sa.ubicacion_id
       where sa.producto_id = v_prod and u.sucursal_id = v_suc and sa.cantidad_base > 0
       order by sa.cantidad_base desc
    loop
      exit when v_restante <= 0;
      v_toma := least(v_restante, v_ub.cantidad_base);
      v_kid := registrar_salida(v_pres_base, v_ub.ubicacion_id, v_toma,
        'Venta #' || v_venta_id, p_usuario, current_date,
        'venta:' || v_venta_id || ':l' || v_ix || ':p' || v_prod || ':u' || v_ub.ubicacion_id, false);
      if v_primer_kid is null then v_primer_kid := v_kid; end if;
      v_restante := v_restante - v_toma;
    end loop;

    if v_restante > 0 then
      if not v_libre then
        raise exception 'Stock insuficiente (carrera) producto %', v_prod;
      end if;
      select sa.ubicacion_id into v_ubic_sobregiro
        from stock_actual sa join ubicacion u on u.id = sa.ubicacion_id
       where sa.producto_id = v_prod and u.sucursal_id = v_suc
       order by sa.cantidad_base desc limit 1;
      if v_ubic_sobregiro is null then
        select id into v_ubic_sobregiro from ubicacion
         where sucursal_id = v_suc order by id limit 1;
      end if;
      if v_ubic_sobregiro is null then
        raise exception 'La sucursal % no tiene ninguna ubicación configurada', v_suc;
      end if;

      v_kid := registrar_salida(v_pres_base, v_ubic_sobregiro, v_restante,
        'Venta #' || v_venta_id, p_usuario, current_date,
        'venta:' || v_venta_id || ':l' || v_ix || ':p' || v_prod || ':sobregiro', true);
      if v_primer_kid is null then v_primer_kid := v_kid; end if;
      v_restante := 0;
    end if;

    v_sub := round(v_unit * v_cant_pres, 2);
    insert into venta_linea (venta_id, producto_id, presentacion_id, cantidad,
                             cantidad_presentacion, precio_lista, precio_unitario,
                             kardex_transaccion_id)
    values (v_venta_id, v_prod, v_pres, v_cant, v_cant_pres, v_lista, v_unit, v_primer_kid);
    v_subtotal := v_subtotal + v_sub;
  end loop;

  v_total := round(v_subtotal - coalesce(p_descuento_total, 0), 2);
  select coalesce(sum((p->>'monto')::numeric), 0) into v_pagado from jsonb_array_elements(p_pagos) p;
  if round(v_pagado, 2) <> v_total then
    raise exception 'El pago (%) no coincide con el total (%)', v_pagado, v_total;
  end if;
  if v_total<=0 or exists(select 1 from jsonb_array_elements(p_pagos) p where (p->>'monto') is null or (p->>'monto')::numeric<=0 or (p->>'monto')::numeric::text in ('NaN','Infinity','-Infinity')) then
    raise exception 'El total y los pagos deben ser positivos';
  end if;
  if (select count(*) from jsonb_array_elements(p_pagos) p where p->>'metodo'='SALDO_FAVOR')>1 then raise exception 'Solo se admite una aplicación de saldo por venta';end if;
  update public.venta set subtotal=v_subtotal,total=v_total,descuento_total=coalesce(p_descuento_total,0) where id=v_venta_id;
  for v_pago in select * from jsonb_array_elements(p_pagos) loop
    if v_pago->>'metodo'='SALDO_FAVOR' then
      insert into public.saldo_cliente_uso(cliente_id,hermes_cliente_id,venta_id,sesion_caja_id,monto,saldo_antes,saldo_despues,idempotencia_clave,solicitud,creado_por)
      values(p_cliente_id,0,v_venta_id,p_sesion_caja_id,(v_pago->>'monto')::numeric,0,0,'saldo-venta:'||v_venta_id,
        jsonb_build_object('lineas',p_lineas,'pagos',p_pagos,'cliente',p_cliente_id,'sesion',p_sesion_caja_id,'descuento',coalesce(p_descuento_total,0)),'');
      continue;
    end if;
    v_metodo := (v_pago->>'metodo')::metodo_pago;

    -- A2: "recibido" (solo tiene sentido en EFECTIVO, pero se valida siempre que
    -- venga) nunca entra en la suma de p_pagos — el chequeo de arriba ya corrió.
    v_recibido := (v_pago->>'recibido')::numeric;
    if v_recibido is not null and v_recibido < (v_pago->>'monto')::numeric then
      raise exception 'El monto recibido (%) no puede ser menor al monto del pago (%)', v_recibido, (v_pago->>'monto')::numeric;
    end if;

    -- A3: QR/TRANSFERENCIA quedan PENDIENTE de verificación (Caja-2 los concilia);
    -- EFECTIVO (y cualquier otro método que llegue por acá) no aplica.
    v_estado_verif := case when v_metodo in ('QR', 'TRANSFERENCIA') then 'PENDIENTE' else 'NO_APLICA' end;

    insert into venta_pago (venta_id, metodo, monto, recibido, referencia, estado_verificacion)
    values (v_venta_id, v_metodo, (v_pago->>'monto')::numeric, v_recibido, v_pago->>'referencia', v_estado_verif);
    insert into movimiento_caja (sesion_caja_id, tipo, metodo, monto, venta_id, creado_por)
    values (p_sesion_caja_id, 'VENTA', v_metodo, (v_pago->>'monto')::numeric, v_venta_id, p_usuario);
  end loop;
  update venta set subtotal = v_subtotal, descuento_total = coalesce(p_descuento_total, 0),
                   total = v_total, estado = 'COMPLETADA', completado_en = now()
   where id = v_venta_id;
  return jsonb_build_object('venta_id', v_venta_id, 'numero', v_numero, 'subtotal', v_subtotal,
                            'descuento_total', coalesce(p_descuento_total, 0), 'total', v_total);
end;
$function$
;
create function public.registrar_venta_con_saldo(p_lineas jsonb,p_pagos jsonb,p_sesion_caja_id bigint,p_cliente_id bigint,p_saldo_favor numeric,p_descuento_total numeric default 0,p_usuario text default null,p_idempotencia text default null)
returns jsonb language plpgsql set search_path=pg_catalog,public as $$
declare resultado jsonb; v public.venta%rowtype; u public.saldo_cliente_uso%rowtype; pagos jsonb; actor text;
begin
 if auth.uid() is null or not exists(select 1 from public.perfil where id=auth.uid() and activo and rol in ('admin','gerente','cajero')) then raise exception 'Operador no autorizado' using errcode='42501';end if;
 select coalesce(email,id::text) into actor from public.perfil where id=auth.uid();
 if p_saldo_favor is null or p_saldo_favor<=0 or p_saldo_favor::text in ('NaN','Infinity','-Infinity') or p_idempotencia is null or btrim(p_idempotencia)='' or length(p_idempotencia)>200 then raise exception 'Importe o clave de saldo inválidos';end if;
 if p_pagos is null or jsonb_typeof(p_pagos)<>'array' or exists(select 1 from jsonb_array_elements(p_pagos) p where p->>'metodo'='SALDO_FAVOR') then raise exception 'Pagos nuevos inválidos';end if;
 perform pg_advisory_xact_lock(hashtextextended('venta:'||p_idempotencia,0));
 select * into v from public.venta where idempotencia_clave=p_idempotencia;
 if found and (v.cliente_id is distinct from p_cliente_id or v.sesion_caja_id is distinct from p_sesion_caja_id or v.saldo_favor_aplicado<>round(p_saldo_favor,2) or v.estado::text='ANULADA') then raise exception 'La clave corresponde a otra venta o está anulada';end if;
 pagos:=p_pagos||jsonb_build_array(jsonb_build_object('metodo','SALDO_FAVOR','monto',round(p_saldo_favor,2)));
 resultado:=public.registrar_venta(p_lineas,pagos,p_sesion_caja_id,p_cliente_id,p_descuento_total,actor,p_idempotencia);
 select * into u from public.saldo_cliente_uso where venta_id=(resultado->>'venta_id')::bigint;
 if not found then raise exception 'No se pudo verificar el consumo de saldo';end if;
 return resultado||jsonb_build_object('saldo_favor_aplicado',u.monto,'saldo_favor_restante',greatest(-u.saldo_despues,0),'cliente_acreedor',u.saldo_antes<0);
end $$;
revoke all on function public.registrar_venta_con_saldo(jsonb,jsonb,bigint,bigint,numeric,numeric,text,text) from public,anon;
grant execute on function public.registrar_venta_con_saldo(jsonb,jsonb,bigint,bigint,numeric,numeric,text,text) to authenticated;

create or replace view hermes.v_partida_estado with(security_invoker=true) as  SELECT pa.id AS partida_id,
    pa.cliente_id,
    pa.pedido_id,
    pa.referencia,
    pa.documento_interno,
    pa.estado,
    pa.total,
    pa.creado_en,
    pa.fecha_entrega,
    pa.plazo_dias,
    (COALESCE(ap.imputado, 0::numeric) + COALESCE(sf.aplicado, 0::numeric)) AS imputado,
    pa.total - (COALESCE(ap.imputado, 0::numeric) + COALESCE(sf.aplicado, 0::numeric)) AS pendiente,
    COALESCE(rev.en_revision, 0::numeric) AS en_revision,
    ( SELECT count(*) AS count
           FROM hermes.hito h
          WHERE h.partida_abierta_id = pa.id AND h.obligatorio) AS hitos_obligatorios,
    ( SELECT count(*) AS count
           FROM hermes.hito h
          WHERE h.partida_abierta_id = pa.id AND h.obligatorio AND h.estado = 'COMPLETO'::hermes.estado_hito) AS hitos_cumplidos,
    ( SELECT h.nombre
           FROM hermes.hito h
          WHERE h.partida_abierta_id = pa.id AND h.obligatorio AND h.estado <> 'COMPLETO'::hermes.estado_hito
          ORDER BY h.orden
         LIMIT 1) AS proximo_hito,
    CURRENT_DATE - (pa.creado_en AT TIME ZONE 'America/La_Paz'::text)::date AS dias_abierta
   FROM hermes.partida_abierta pa
     LEFT JOIN (SELECT a.partida_id,sum(a.monto) aplicado FROM hermes.saldo_uso_partida a
       JOIN public.saldo_cliente_uso u ON u.id=a.uso_id WHERE u.anulado_en IS NULL GROUP BY a.partida_id) sf ON sf.partida_id=pa.id
     LEFT JOIN ( SELECT ap_1.partida_id,
            sum(ap_1.monto) AS imputado
           FROM hermes.pago_aplicacion ap_1
             JOIN hermes.pago p ON p.id = ap_1.pago_id
          WHERE p.estado = ANY (ARRAY['CONFIRMADO'::hermes.estado_pago, 'ACREDITADO'::hermes.estado_pago])
          GROUP BY ap_1.partida_id) ap ON ap.partida_id = pa.id
     LEFT JOIN ( SELECT ap_1.partida_id,
            sum(ap_1.monto) AS en_revision
           FROM hermes.pago_aplicacion ap_1
             JOIN hermes.pago p ON p.id = ap_1.pago_id
          WHERE p.estado = 'PROPUESTO'::hermes.estado_pago
          GROUP BY ap_1.partida_id) rev ON rev.partida_id = pa.id;;

create or replace view hermes.v_anticipo_cliente with(security_invoker=true) as  SELECT p.id AS pago_id,
    p.cliente_id,
    p.monto,
    (COALESCE(ap.imputado, 0::numeric) + COALESCE(sf.aplicado,0::numeric)) AS imputado,
    p.monto - (COALESCE(ap.imputado, 0::numeric) + COALESCE(sf.aplicado,0::numeric)) AS saldo_favor,
    p.no_imputar,
    p.medio,
    p.estado,
    p.referencia,
    p.fecha_recepcion,
    p.fecha_acreditacion,
    p.confirmado_en,
    p.evidencia_id,
    e.storage_path AS comprobante_path,
    e.nombre_original AS comprobante_nombre,
    p.evidencia_id IS NOT NULL AS tiene_comprobante
   FROM hermes.pago p
     LEFT JOIN (SELECT m.pago_id,sum(f.monto) aplicado FROM hermes.saldo_uso_fuente f
       JOIN public.saldo_cliente_uso u ON u.id=f.uso_id JOIN hermes.movimiento_cuenta m ON m.id=f.movimiento_id
       WHERE u.anulado_en IS NULL AND m.pago_id IS NOT NULL GROUP BY m.pago_id) sf ON sf.pago_id=p.id
     LEFT JOIN hermes.evidencia e ON e.id = p.evidencia_id
     LEFT JOIN ( SELECT ap_1.pago_id,
            sum(ap_1.monto) AS imputado
           FROM hermes.pago_aplicacion ap_1
          GROUP BY ap_1.pago_id) ap ON ap.pago_id = p.id
  WHERE (p.estado = ANY (ARRAY['CONFIRMADO'::hermes.estado_pago, 'ACREDITADO'::hermes.estado_pago])) AND (p.monto - (COALESCE(ap.imputado, 0::numeric) + COALESCE(sf.aplicado,0::numeric))) > 0::numeric;;

CREATE OR REPLACE FUNCTION public.resumen_turno(p_sesion_id bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_rol text;
  v_ses sesion_caja%rowtype;
  v_ventas jsonb; v_ventas_retail jsonb; v_ventas_vtd jsonb;
  v_anticipos jsonb; v_anulaciones jsonb; v_gastos jsonb;
  v_remesas numeric; v_inyecciones numeric; v_cantidad_ventas int; v_cantidad_vtd int;
  v_pendientes int; v_esperado numeric; v_neto numeric; v_rechazados jsonb;
  v_vtd_pend jsonb;
begin
  v_rol := app_rol_actual();
  if v_rol is null then raise exception 'No autorizado'; end if;

  select * into v_ses from sesion_caja where id = p_sesion_id;
  if not found then raise exception 'Sesión % no existe', p_sesion_id; end if;

  if v_rol = 'cajero' and v_ses.cajero_id is distinct from auth.uid() then
    raise exception 'Solo podés ver tu propio turno';
  elsif v_rol not in ('cajero', 'gerente', 'admin') then
    raise exception 'No autorizado';
  end if;

  select coalesce(jsonb_object_agg(metodo, monto), '{}'::jsonb) into v_ventas
    from (select metodo::text as metodo, sum(monto) as monto from movimiento_caja
           where sesion_caja_id = p_sesion_id and tipo = 'VENTA' group by metodo) t;

  select coalesce(jsonb_object_agg(metodo, monto), '{}'::jsonb) into v_ventas_retail
    from (select m.metodo::text as metodo, sum(m.monto) as monto
            from movimiento_caja m left join venta v on v.id = m.venta_id
           where m.sesion_caja_id = p_sesion_id and m.tipo = 'VENTA'
             and coalesce(v.numero, '') not like 'VTD-%'
           group by m.metodo) t;

  select coalesce(jsonb_object_agg(metodo, monto), '{}'::jsonb) into v_ventas_vtd
    from (select m.metodo::text as metodo, sum(m.monto) as monto
            from movimiento_caja m join venta v on v.id = m.venta_id
           where m.sesion_caja_id = p_sesion_id and m.tipo = 'VENTA'
             and v.numero like 'VTD-%'
           group by m.metodo) t;

  select coalesce(jsonb_object_agg(metodo, monto), '{}'::jsonb) into v_anticipos
    from (select metodo::text as metodo, sum(monto) as monto from movimiento_caja
           where sesion_caja_id = p_sesion_id and tipo = 'ANTICIPO' and not fuera_de_arqueo group by metodo) t;

  select coalesce(jsonb_object_agg(metodo, monto), '{}'::jsonb) into v_anulaciones
    from (select metodo::text as metodo, sum(monto) as monto from movimiento_caja
           where sesion_caja_id = p_sesion_id and tipo = 'ANULACION' group by metodo) t;

  select coalesce(jsonb_object_agg(lower(estado), monto), '{}'::jsonb) into v_gastos
    from (select g.estado, sum(g.monto) as monto from caja_gasto g
           where g.sesion_caja_id = p_sesion_id group by g.estado) t;

  select coalesce(sum(monto), 0) into v_remesas from movimiento_caja
   where sesion_caja_id = p_sesion_id and subtipo = 'REMESA';
  select coalesce(sum(monto), 0) into v_inyecciones from movimiento_caja
   where sesion_caja_id = p_sesion_id and subtipo = 'INYECCION';

  select count(*) into v_cantidad_ventas from venta
   where sesion_caja_id = p_sesion_id and estado = 'COMPLETADA'
     and coalesce(numero, '') not like 'VTD-%';

  select count(distinct m.venta_id) into v_cantidad_vtd
    from movimiento_caja m join venta v on v.id = m.venta_id
   where m.sesion_caja_id = p_sesion_id and m.tipo = 'VENTA' and v.numero like 'VTD-%';

  select jsonb_build_object('cantidad', count(*), 'total', coalesce(sum(total), 0))
    into v_vtd_pend
    from v_vtd_por_cobrar;

  select count(*) into v_pendientes from venta_pago vp
    join venta v on v.id = vp.venta_id
   where vp.estado_verificacion = 'PENDIENTE'
     and exists (select 1 from movimiento_caja m
                  where m.venta_id = v.id and m.sesion_caja_id = p_sesion_id and m.tipo = 'VENTA');

  select coalesce(jsonb_agg(jsonb_build_object('venta_id', v.id, 'numero', v.numero, 'metodo', vp.metodo, 'monto', vp.monto)), '[]'::jsonb)
    into v_rechazados
    from venta_pago vp join venta v on v.id = vp.venta_id
   where vp.estado_verificacion = 'RECHAZADO'
     and exists (select 1 from movimiento_caja m
                  where m.venta_id = v.id and m.sesion_caja_id = p_sesion_id and m.tipo = 'VENTA');

  if v_rol in ('gerente', 'admin') then
    select coalesce(sum(case when tipo in ('VENTA', 'ANTICIPO', 'INGRESO') then monto
                             when tipo in ('EGRESO', 'ANULACION') then -monto else 0 end), 0)
      into v_neto
    from movimiento_caja where sesion_caja_id = p_sesion_id and metodo = 'EFECTIVO' and not fuera_de_arqueo;
    v_esperado := v_ses.monto_apertura + v_neto;
  else
    v_esperado := null;
  end if;

  return jsonb_build_object(
    'apertura', v_ses.monto_apertura,
    'saldo_favor_aplicado',(select coalesce(sum(monto),0) from public.saldo_cliente_uso where sesion_caja_id=p_sesion_id and anulado_en is null),
    'ventas_total',(select coalesce(sum(total),0) from public.venta where sesion_caja_id=p_sesion_id and estado::text='COMPLETADA' and numero like 'VTA-%'),
    'ventas_acreedores',(select count(*) from public.venta where sesion_caja_id=p_sesion_id and estado::text='COMPLETADA' and cliente_acreedor),
    'ventas', v_ventas,
    'ventas_retail', v_ventas_retail,
    'ventas_vtd', v_ventas_vtd,
    'anticipos', v_anticipos, 'cobros_fuera_arqueo', (select coalesce(sum(monto), 0) from movimiento_caja where sesion_caja_id = p_sesion_id and fuera_de_arqueo),
    'anulaciones', v_anulaciones,
    'gastos', v_gastos,
    'remesas', v_remesas,
    'inyecciones', v_inyecciones,
    'cantidad_ventas', v_cantidad_ventas,
    'cantidad_vtd_cobradas', v_cantidad_vtd,
    'vtd_por_cobrar', v_vtd_pend,
    'pagos_pendientes_verificacion', v_pendientes,
    'pagos_rechazados', v_rechazados,
    'diferencia_relevo', v_ses.diferencia_relevo,
    'esperado_efectivo', v_esperado
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION hermes.anular_partida(p_partida_id bigint, p_motivo text, p_usuario text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'hermes', 'public'
AS $function$
declare
  v_pa       record;
  v_aplicado numeric;
begin
 if not hermes.contexto_confiable() and not public.hermes_tiene_acceso() then
 raise exception 'Sin acceso a Hermes' using errcode='42501'; end if;
  if not contexto_confiable() and rol_actual() <> 'gerente' then
    raise exception 'Solo el rol gerente puede anular una partida';
  end if;
  if p_motivo is null or btrim(p_motivo) = '' then
    raise exception 'El motivo es obligatorio';
  end if;

  select * into v_pa from partida_abierta where id = p_partida_id for update;
  if not found then raise exception 'La partida % no existe', p_partida_id; end if;
  if exists(select 1 from hermes.saldo_uso_partida a join public.saldo_cliente_uso u on u.id=a.uso_id where a.partida_id=p_partida_id and u.anulado_en is null) then
    raise exception 'Esta partida tiene saldo a favor aplicado. Anula el pedido en Seller para restaurarlo de forma conjunta.';
  end if;
  if v_pa.estado <> 'ABIERTA' then
    raise exception 'La partida % está en estado % y no se puede anular', p_partida_id, v_pa.estado;
  end if;

  select coalesce(sum(pap.monto), 0) into v_aplicado
    from pago_aplicacion pap
    join pago pg on pg.id = pap.pago_id
   where pap.partida_id = p_partida_id
     and pg.estado in ('CONFIRMADO', 'ACREDITADO');
  if v_aplicado > 0 then
    raise exception 'La partida % tiene Bs % aplicados: no se puede anular', p_partida_id, v_aplicado;
  end if;

  update partida_abierta
     set estado = 'ANULADA', anulada_en = now(), anulada_por = p_usuario,
         motivo_anulacion = btrim(p_motivo)
   where id = p_partida_id;

  insert into movimiento_cuenta (
    cliente_id, partida_id, tipo, monto, idempotencia_clave,
    fecha_efectiva, referencia, motivo, creado_por
  ) values (
    v_pa.cliente_id, p_partida_id, 'NOTA_CREDITO', -v_pa.total,
    'anulacion-partida-' || p_partida_id, current_date,
    v_pa.documento_interno, 'Anulación: ' || btrim(p_motivo), p_usuario
  );
end;
$function$
;
notify pgrst,'reload schema';
