import { Copy, Eye, FileDown, Plus, Printer, ShoppingCart } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import type { QuoteDraft, QuoteWorkflowStatus } from '../../application/shared/models'
import { orderService, quoteService, sensitiveOperations } from '../../infrastructure/mock/services'
import { products, getPrice } from '../../data/products'
import { formatMoney, money } from '../../domain/common/money'
import { FeatureShell, FeatureState, FeatureToolbar, statusLabel } from '../shared/FeatureShell'
import { Modal } from '../../components/Modal'

const total = (quote: QuoteDraft) => quote.lines.reduce((sum, line) => sum + Math.round(line.unitPriceCents * line.quantity * (10_000 - line.discountBasisPoints) / 10_000), 0) - quote.generalDiscountCents

export function QuotationsPage({ notify, onOrderCreated, readOnly = false }: { notify: (message: string) => void; onOrderCreated: () => void; readOnly?: boolean }) {
  const [quotes, setQuotes] = useState<QuoteDraft[]>([])
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading')
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState<'all' | QuoteWorkflowStatus>('all')
  const [editing, setEditing] = useState<QuoteDraft | null>(null)
  const [preview, setPreview] = useState<QuoteDraft | null>(null)
  const load = () => quoteService.list().then((items) => { setQuotes(items); setStatus('ready') }).catch(() => setStatus('error'))
  useEffect(() => { void load() }, [])
  const filtered = useMemo(() => quotes.filter((quote) => (filter === 'all' || quote.status === filter) && `${quote.number} ${quote.customerName} ${quote.status}`.toLowerCase().includes(query.toLowerCase())), [quotes, query, filter])
  const create = () => { if(readOnly){notify('Modo solo lectura');return} setEditing({ id: crypto.randomUUID(), number: `COT-MOCK-${Date.now().toString().slice(-5)}`, customerId: 'c1', customerName: 'Librería San Marcos', channel: 'mayoreo', status: 'draft', validUntil: new Date(Date.now() + 15 * 86400000).toISOString().slice(0, 10), terms: 'Contado', notes: '', generalDiscountCents: 0, createdAt: new Date().toISOString(), lines: [] }) }
  const save = async (quote: QuoteDraft) => { if(readOnly){notify('Modo solo lectura');return} await quoteService.save(quote); setEditing(null); await load(); notify('Cotización guardada localmente') }
  const duplicate = async (id: string) => { if(readOnly){notify('Modo solo lectura');return} await quoteService.duplicate(id); await load(); notify('Cotización duplicada') }
  const convert = async (quote: QuoteDraft) => {
    if(readOnly){notify('Modo solo lectura');return}
    if (!confirm(`¿Convertir ${quote.number} en pedido mock?`)) return
    const snapshot = await sensitiveOperations.execute('convert_quote',quote.id,()=>quoteService.markConverted(quote.id, crypto.randomUUID()))
    await orderService.save({ id: snapshot.id, number: snapshot.number, customerName: snapshot.customer.name, channel: quote.channel, status: 'draft', createdAt: snapshot.createdAt, sourceQuoteId: quote.id, lines: snapshot.items.map((line) => ({ id: line.id, productId: line.product.productId, name: line.product.name, sku: line.product.sku, quantity: line.quantity, unitPriceCents: line.appliedPrice.cents, discountBasisPoints: line.discountBasisPoints, prepared: 0, allocations: [] })), events: [{ at: new Date().toLocaleString('es-BO'), label: 'Pedido creado desde cotización', detail: `Snapshots conservados desde ${quote.number}` }] })
    await load()
    onOrderCreated()
    notify('Pedido simulado creado conservando snapshots')
  }
  return <FeatureShell eyebrow="GESTIÓN COMERCIAL" title="Cotizaciones" subtitle="Propuestas para clientes mayoristas e institucionales" action={<button className="primary-button" onClick={create}><Plus /> Nueva cotización</button>}><FeatureToolbar query={query} onQuery={setQuery} placeholder="Buscar por número, cliente o estado..."><select value={filter} onChange={(e) => setFilter(e.target.value as typeof filter)}><option value="all">Todos los estados</option>{['draft','sent','negotiating','approved','rejected','expired','converted'].map((value) => <option key={value} value={value}>{statusLabel[value]}</option>)}</select><input type="date" aria-label="Filtrar por fecha" /></FeatureToolbar>{status === 'loading' ? <FeatureState type="loading" text="Cargando cotizaciones" /> : status === 'error' ? <FeatureState type="error" text="No se pudieron cargar" /> : !filtered.length ? <FeatureState type={quotes.length ? 'no-results' : 'empty'} text="No hay cotizaciones" /> : <div className="feature-table"><div className="table-head"><span>Número / fecha</span><span>Cliente</span><span>Canal</span><span>Estado</span><span>Total</span><span>Acciones</span></div>{filtered.map((quote) => <article key={quote.id}><div><strong>{quote.number}</strong><small>{new Date(quote.createdAt).toLocaleDateString('es-BO')}</small></div><div><strong>{quote.customerName}</strong><small>Válida hasta {quote.validUntil}</small></div><span className="channel-chip">{quote.channel}</span><span className={`status-chip ${quote.status}`}>{statusLabel[quote.status]}</span><strong>{formatMoney(money(Math.max(0,total(quote))))}</strong><div className="row-actions"><button title="Vista previa" onClick={() => setPreview(quote)}><Eye /></button><button title="Duplicar" onClick={() => duplicate(quote.id)}><Copy /></button><button title="Editar" disabled={quote.status !== 'draft'} onClick={() => setEditing(quote)}>Editar</button>{quote.status === 'approved' && <button title="Convertir en pedido" onClick={() => convert(quote)}><ShoppingCart /></button>}</div></article>)}</div>}{editing && <QuoteEditor quote={editing} onClose={() => setEditing(null)} onSave={save} />}{preview && <DocumentPreview quote={preview} onClose={() => setPreview(null)} />}</FeatureShell>
}

function QuoteEditor({ quote, onClose, onSave }: { quote: QuoteDraft; onClose: () => void; onSave: (quote: QuoteDraft) => void }) {
  const [value, setValue] = useState(structuredClone(quote))
  const addProduct = () => { const product = products[value.lines.length % products.length]; if (value.lines.some((line) => line.productId === String(product.id))) return; setValue({ ...value, lines: [...value.lines, { id: crypto.randomUUID(), productId: String(product.id), name: product.nombre, sku: product.sku, quantity: 1, unitPriceCents: Math.round(getPrice(product, value.channel) * 100), discountBasisPoints: 0 }] }) }
  return <Modal title={quote.lines.length ? `Editar ${quote.number}` : 'Nueva cotización'} subtitle="Los cambios se guardan solo en este dispositivo" onClose={onClose} wide><div className="modal-body quote-editor"><div className="form-grid"><label>Cliente<select value={value.customerName} onChange={(e) => setValue({ ...value, customerName: e.target.value })}><option>Librería San Marcos</option><option>Colegio Nueva Esperanza</option><option>Papelería El Estudiante</option></select></label><label>Canal<select value={value.channel} onChange={(e) => setValue({ ...value, channel: e.target.value as QuoteDraft['channel'] })}><option value="mayoreo">Mayoreo</option><option value="institucional">Institucional</option></select></label><label>Vigencia<input type="date" value={value.validUntil} onChange={(e) => setValue({ ...value, validUntil: e.target.value })} /></label><label>Descuento general (Bs)<input type="number" min="0" value={value.generalDiscountCents / 100} onChange={(e) => setValue({ ...value, generalDiscountCents: Math.max(0, Math.round(Number(e.target.value) * 100)) })} /></label><label className="full">Condiciones comerciales<input value={value.terms} onChange={(e) => setValue({ ...value, terms: e.target.value })} /></label><label className="full">Observaciones<textarea rows={2} value={value.notes} onChange={(e) => setValue({ ...value, notes: e.target.value })} /></label></div><div className="editor-lines"><header><strong>Productos</strong><button onClick={addProduct}><Plus /> Agregar producto</button></header>{value.lines.map((line) => <div key={line.id}><span><strong>{line.name}</strong><small>{line.sku}</small></span><input aria-label={`Cantidad ${line.name}`} type="number" min="1" value={line.quantity} onChange={(e) => setValue({ ...value, lines: value.lines.map((item) => item.id === line.id ? { ...item, quantity: Math.max(1, Number(e.target.value)) } : item) })} /><input aria-label={`Descuento ${line.name}`} type="number" min="0" max="100" value={line.discountBasisPoints / 100} onChange={(e) => setValue({ ...value, lines: value.lines.map((item) => item.id === line.id ? { ...item, discountBasisPoints: Math.min(10000, Math.max(0, Number(e.target.value) * 100)) } : item) })} /><strong>{formatMoney(money(line.unitPriceCents))}</strong><button onClick={() => setValue({ ...value, lines: value.lines.filter((item) => item.id !== line.id) })}>×</button></div>)}</div></div><footer className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={!value.lines.length} onClick={() => onSave(value)}>Guardar cotización</button></footer></Modal>
}

function DocumentPreview({ quote, onClose }: { quote: QuoteDraft; onClose: () => void }) {
  return <Modal title="Vista previa de cotización" subtitle="Documento mock · No fiscal" onClose={onClose} wide><div className="print-document quote-a4"><header><div><b>ROARI</b><span>Papelería & Librería</span></div><div><strong>COTIZACIÓN</strong><span>{quote.number}</span></div></header><section><p><b>Cliente:</b> {quote.customerName}</p><p><b>Canal:</b> {quote.channel}</p><p><b>Vigencia:</b> {quote.validUntil}</p></section>{quote.lines.map((line) => <div className="print-line" key={line.id}><span>{line.quantity} × {line.name}</span><strong>{formatMoney(money(line.unitPriceCents * line.quantity))}</strong></div>)}<footer><span>Total</span><strong>{formatMoney(money(Math.max(0,total(quote))))}</strong></footer></div><footer className="modal-actions"><button className="secondary-button" onClick={() => window.print()}><FileDown /> Guardar PDF</button><button className="primary-button" onClick={() => window.print()}><Printer /> Imprimir</button></footer></Modal>
}
